/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsResponseTrendsCrashDiscoveryTrendInner
 */
export interface AnalyticsResponseTrendsCrashDiscoveryTrendInner {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsResponseTrendsCrashDiscoveryTrendInner
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseTrendsCrashDiscoveryTrendInner
     */
    newCrashes?: number;
}

/**
 * Check if a given object implements the AnalyticsResponseTrendsCrashDiscoveryTrendInner interface.
 */
export function instanceOfAnalyticsResponseTrendsCrashDiscoveryTrendInner(value: object): value is AnalyticsResponseTrendsCrashDiscoveryTrendInner {
    return true;
}

export function AnalyticsResponseTrendsCrashDiscoveryTrendInnerFromJSON(json: any): AnalyticsResponseTrendsCrashDiscoveryTrendInner {
    return AnalyticsResponseTrendsCrashDiscoveryTrendInnerFromJSONTyped(json, false);
}

export function AnalyticsResponseTrendsCrashDiscoveryTrendInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseTrendsCrashDiscoveryTrendInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'newCrashes': json['new_crashes'] == null ? undefined : json['new_crashes'],
    };
}

export function AnalyticsResponseTrendsCrashDiscoveryTrendInnerToJSON(json: any): AnalyticsResponseTrendsCrashDiscoveryTrendInner {
    return AnalyticsResponseTrendsCrashDiscoveryTrendInnerToJSONTyped(json, false);
}

export function AnalyticsResponseTrendsCrashDiscoveryTrendInnerToJSONTyped(value?: AnalyticsResponseTrendsCrashDiscoveryTrendInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'new_crashes': value['newCrashes'],
    };
}

