/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * High-level system statistics
 * @export
 * @interface AnalyticsResponseSystemOverview
 */
export interface AnalyticsResponseSystemOverview {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalCampaigns?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    activeCampaigns?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    activeJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalBots?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    onlineBots?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalCrashes?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    uniqueCrashes?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalCorpusEntries?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseSystemOverview
     */
    totalCoverageEdges?: number;
}

/**
 * Check if a given object implements the AnalyticsResponseSystemOverview interface.
 */
export function instanceOfAnalyticsResponseSystemOverview(value: object): value is AnalyticsResponseSystemOverview {
    return true;
}

export function AnalyticsResponseSystemOverviewFromJSON(json: any): AnalyticsResponseSystemOverview {
    return AnalyticsResponseSystemOverviewFromJSONTyped(json, false);
}

export function AnalyticsResponseSystemOverviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseSystemOverview {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCampaigns': json['total_campaigns'] == null ? undefined : json['total_campaigns'],
        'activeCampaigns': json['active_campaigns'] == null ? undefined : json['active_campaigns'],
        'totalJobs': json['total_jobs'] == null ? undefined : json['total_jobs'],
        'activeJobs': json['active_jobs'] == null ? undefined : json['active_jobs'],
        'totalBots': json['total_bots'] == null ? undefined : json['total_bots'],
        'onlineBots': json['online_bots'] == null ? undefined : json['online_bots'],
        'totalCrashes': json['total_crashes'] == null ? undefined : json['total_crashes'],
        'uniqueCrashes': json['unique_crashes'] == null ? undefined : json['unique_crashes'],
        'totalCorpusEntries': json['total_corpus_entries'] == null ? undefined : json['total_corpus_entries'],
        'totalCoverageEdges': json['total_coverage_edges'] == null ? undefined : json['total_coverage_edges'],
    };
}

export function AnalyticsResponseSystemOverviewToJSON(json: any): AnalyticsResponseSystemOverview {
    return AnalyticsResponseSystemOverviewToJSONTyped(json, false);
}

export function AnalyticsResponseSystemOverviewToJSONTyped(value?: AnalyticsResponseSystemOverview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_campaigns': value['totalCampaigns'],
        'active_campaigns': value['activeCampaigns'],
        'total_jobs': value['totalJobs'],
        'active_jobs': value['activeJobs'],
        'total_bots': value['totalBots'],
        'online_bots': value['onlineBots'],
        'total_crashes': value['totalCrashes'],
        'unique_crashes': value['uniqueCrashes'],
        'total_corpus_entries': value['totalCorpusEntries'],
        'total_coverage_edges': value['totalCoverageEdges'],
    };
}

