/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsResponsePerformanceMetrics } from './AnalyticsResponsePerformanceMetrics';
import {
    AnalyticsResponsePerformanceMetricsFromJSON,
    AnalyticsResponsePerformanceMetricsFromJSONTyped,
    AnalyticsResponsePerformanceMetricsToJSON,
    AnalyticsResponsePerformanceMetricsToJSONTyped,
} from './AnalyticsResponsePerformanceMetrics';
import type { AnalyticsResponseTimeRange } from './AnalyticsResponseTimeRange';
import {
    AnalyticsResponseTimeRangeFromJSON,
    AnalyticsResponseTimeRangeFromJSONTyped,
    AnalyticsResponseTimeRangeToJSON,
    AnalyticsResponseTimeRangeToJSONTyped,
} from './AnalyticsResponseTimeRange';
import type { AnalyticsResponseSystemOverview } from './AnalyticsResponseSystemOverview';
import {
    AnalyticsResponseSystemOverviewFromJSON,
    AnalyticsResponseSystemOverviewFromJSONTyped,
    AnalyticsResponseSystemOverviewToJSON,
    AnalyticsResponseSystemOverviewToJSONTyped,
} from './AnalyticsResponseSystemOverview';
import type { AnalyticsResponseResourceUsage } from './AnalyticsResponseResourceUsage';
import {
    AnalyticsResponseResourceUsageFromJSON,
    AnalyticsResponseResourceUsageFromJSONTyped,
    AnalyticsResponseResourceUsageToJSON,
    AnalyticsResponseResourceUsageToJSONTyped,
} from './AnalyticsResponseResourceUsage';
import type { AnalyticsResponseTrends } from './AnalyticsResponseTrends';
import {
    AnalyticsResponseTrendsFromJSON,
    AnalyticsResponseTrendsFromJSONTyped,
    AnalyticsResponseTrendsToJSON,
    AnalyticsResponseTrendsToJSONTyped,
} from './AnalyticsResponseTrends';

/**
 * 
 * @export
 * @interface AnalyticsResponse
 */
export interface AnalyticsResponse {
    /**
     * 
     * @type {AnalyticsResponseTimeRange}
     * @memberof AnalyticsResponse
     */
    timeRange: AnalyticsResponseTimeRange;
    /**
     * When the analytics were generated
     * @type {Date}
     * @memberof AnalyticsResponse
     */
    generatedAt: Date;
    /**
     * 
     * @type {AnalyticsResponseSystemOverview}
     * @memberof AnalyticsResponse
     */
    systemOverview: AnalyticsResponseSystemOverview;
    /**
     * 
     * @type {AnalyticsResponsePerformanceMetrics}
     * @memberof AnalyticsResponse
     */
    performanceMetrics?: AnalyticsResponsePerformanceMetrics;
    /**
     * 
     * @type {AnalyticsResponseResourceUsage}
     * @memberof AnalyticsResponse
     */
    resourceUsage?: AnalyticsResponseResourceUsage;
    /**
     * 
     * @type {AnalyticsResponseTrends}
     * @memberof AnalyticsResponse
     */
    trends?: AnalyticsResponseTrends;
}

/**
 * Check if a given object implements the AnalyticsResponse interface.
 */
export function instanceOfAnalyticsResponse(value: object): value is AnalyticsResponse {
    if (!('timeRange' in value) || value['timeRange'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('systemOverview' in value) || value['systemOverview'] === undefined) return false;
    return true;
}

export function AnalyticsResponseFromJSON(json: any): AnalyticsResponse {
    return AnalyticsResponseFromJSONTyped(json, false);
}

export function AnalyticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeRange': AnalyticsResponseTimeRangeFromJSON(json['time_range']),
        'generatedAt': (new Date(json['generated_at'])),
        'systemOverview': AnalyticsResponseSystemOverviewFromJSON(json['system_overview']),
        'performanceMetrics': json['performance_metrics'] == null ? undefined : AnalyticsResponsePerformanceMetricsFromJSON(json['performance_metrics']),
        'resourceUsage': json['resource_usage'] == null ? undefined : AnalyticsResponseResourceUsageFromJSON(json['resource_usage']),
        'trends': json['trends'] == null ? undefined : AnalyticsResponseTrendsFromJSON(json['trends']),
    };
}

export function AnalyticsResponseToJSON(json: any): AnalyticsResponse {
    return AnalyticsResponseToJSONTyped(json, false);
}

export function AnalyticsResponseToJSONTyped(value?: AnalyticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time_range': AnalyticsResponseTimeRangeToJSON(value['timeRange']),
        'generated_at': ((value['generatedAt']).toISOString()),
        'system_overview': AnalyticsResponseSystemOverviewToJSON(value['systemOverview']),
        'performance_metrics': AnalyticsResponsePerformanceMetricsToJSON(value['performanceMetrics']),
        'resource_usage': AnalyticsResponseResourceUsageToJSON(value['resourceUsage']),
        'trends': AnalyticsResponseTrendsToJSON(value['trends']),
    };
}

