/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsResponseTrendsJobCompletionTrendInner
 */
export interface AnalyticsResponseTrendsJobCompletionTrendInner {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsResponseTrendsJobCompletionTrendInner
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseTrendsJobCompletionTrendInner
     */
    completedJobs?: number;
}

/**
 * Check if a given object implements the AnalyticsResponseTrendsJobCompletionTrendInner interface.
 */
export function instanceOfAnalyticsResponseTrendsJobCompletionTrendInner(value: object): value is AnalyticsResponseTrendsJobCompletionTrendInner {
    return true;
}

export function AnalyticsResponseTrendsJobCompletionTrendInnerFromJSON(json: any): AnalyticsResponseTrendsJobCompletionTrendInner {
    return AnalyticsResponseTrendsJobCompletionTrendInnerFromJSONTyped(json, false);
}

export function AnalyticsResponseTrendsJobCompletionTrendInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseTrendsJobCompletionTrendInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'completedJobs': json['completed_jobs'] == null ? undefined : json['completed_jobs'],
    };
}

export function AnalyticsResponseTrendsJobCompletionTrendInnerToJSON(json: any): AnalyticsResponseTrendsJobCompletionTrendInner {
    return AnalyticsResponseTrendsJobCompletionTrendInnerToJSONTyped(json, false);
}

export function AnalyticsResponseTrendsJobCompletionTrendInnerToJSONTyped(value?: AnalyticsResponseTrendsJobCompletionTrendInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'completed_jobs': value['completedJobs'],
    };
}

