/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsResponseTrendsCoverageGrowthTrendInner
 */
export interface AnalyticsResponseTrendsCoverageGrowthTrendInner {
    /**
     * 
     * @type {Date}
     * @memberof AnalyticsResponseTrendsCoverageGrowthTrendInner
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseTrendsCoverageGrowthTrendInner
     */
    totalCoverage?: number;
}

/**
 * Check if a given object implements the AnalyticsResponseTrendsCoverageGrowthTrendInner interface.
 */
export function instanceOfAnalyticsResponseTrendsCoverageGrowthTrendInner(value: object): value is AnalyticsResponseTrendsCoverageGrowthTrendInner {
    return true;
}

export function AnalyticsResponseTrendsCoverageGrowthTrendInnerFromJSON(json: any): AnalyticsResponseTrendsCoverageGrowthTrendInner {
    return AnalyticsResponseTrendsCoverageGrowthTrendInnerFromJSONTyped(json, false);
}

export function AnalyticsResponseTrendsCoverageGrowthTrendInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseTrendsCoverageGrowthTrendInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'totalCoverage': json['total_coverage'] == null ? undefined : json['total_coverage'],
    };
}

export function AnalyticsResponseTrendsCoverageGrowthTrendInnerToJSON(json: any): AnalyticsResponseTrendsCoverageGrowthTrendInner {
    return AnalyticsResponseTrendsCoverageGrowthTrendInnerToJSONTyped(json, false);
}

export function AnalyticsResponseTrendsCoverageGrowthTrendInnerToJSONTyped(value?: AnalyticsResponseTrendsCoverageGrowthTrendInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'total_coverage': value['totalCoverage'],
    };
}

