/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resource utilization statistics
 * @export
 * @interface AnalyticsResponseResourceUsage
 */
export interface AnalyticsResponseResourceUsage {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseResourceUsage
     */
    cpuUtilizationPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseResourceUsage
     */
    memoryUsageBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseResourceUsage
     */
    storageUsageBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponseResourceUsage
     */
    networkThroughputBps?: number;
}

/**
 * Check if a given object implements the AnalyticsResponseResourceUsage interface.
 */
export function instanceOfAnalyticsResponseResourceUsage(value: object): value is AnalyticsResponseResourceUsage {
    return true;
}

export function AnalyticsResponseResourceUsageFromJSON(json: any): AnalyticsResponseResourceUsage {
    return AnalyticsResponseResourceUsageFromJSONTyped(json, false);
}

export function AnalyticsResponseResourceUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponseResourceUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'cpuUtilizationPercent': json['cpu_utilization_percent'] == null ? undefined : json['cpu_utilization_percent'],
        'memoryUsageBytes': json['memory_usage_bytes'] == null ? undefined : json['memory_usage_bytes'],
        'storageUsageBytes': json['storage_usage_bytes'] == null ? undefined : json['storage_usage_bytes'],
        'networkThroughputBps': json['network_throughput_bps'] == null ? undefined : json['network_throughput_bps'],
    };
}

export function AnalyticsResponseResourceUsageToJSON(json: any): AnalyticsResponseResourceUsage {
    return AnalyticsResponseResourceUsageToJSONTyped(json, false);
}

export function AnalyticsResponseResourceUsageToJSONTyped(value?: AnalyticsResponseResourceUsage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu_utilization_percent': value['cpuUtilizationPercent'],
        'memory_usage_bytes': value['memoryUsageBytes'],
        'storage_usage_bytes': value['storageUsageBytes'],
        'network_throughput_bps': value['networkThroughputBps'],
    };
}

