/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Performance and efficiency metrics
 * @export
 * @interface AnalyticsResponsePerformanceMetrics
 */
export interface AnalyticsResponsePerformanceMetrics {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponsePerformanceMetrics
     */
    avgJobCompletionTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponsePerformanceMetrics
     */
    avgExecutionsPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponsePerformanceMetrics
     */
    avgCoveragePerHour?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponsePerformanceMetrics
     */
    crashDiscoveryRatePerHour?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsResponsePerformanceMetrics
     */
    systemEfficiencyScore?: number;
}

/**
 * Check if a given object implements the AnalyticsResponsePerformanceMetrics interface.
 */
export function instanceOfAnalyticsResponsePerformanceMetrics(value: object): value is AnalyticsResponsePerformanceMetrics {
    return true;
}

export function AnalyticsResponsePerformanceMetricsFromJSON(json: any): AnalyticsResponsePerformanceMetrics {
    return AnalyticsResponsePerformanceMetricsFromJSONTyped(json, false);
}

export function AnalyticsResponsePerformanceMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsResponsePerformanceMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'avgJobCompletionTimeSeconds': json['avg_job_completion_time_seconds'] == null ? undefined : json['avg_job_completion_time_seconds'],
        'avgExecutionsPerSecond': json['avg_executions_per_second'] == null ? undefined : json['avg_executions_per_second'],
        'avgCoveragePerHour': json['avg_coverage_per_hour'] == null ? undefined : json['avg_coverage_per_hour'],
        'crashDiscoveryRatePerHour': json['crash_discovery_rate_per_hour'] == null ? undefined : json['crash_discovery_rate_per_hour'],
        'systemEfficiencyScore': json['system_efficiency_score'] == null ? undefined : json['system_efficiency_score'],
    };
}

export function AnalyticsResponsePerformanceMetricsToJSON(json: any): AnalyticsResponsePerformanceMetrics {
    return AnalyticsResponsePerformanceMetricsToJSONTyped(json, false);
}

export function AnalyticsResponsePerformanceMetricsToJSONTyped(value?: AnalyticsResponsePerformanceMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_job_completion_time_seconds': value['avgJobCompletionTimeSeconds'],
        'avg_executions_per_second': value['avgExecutionsPerSecond'],
        'avg_coverage_per_hour': value['avgCoveragePerHour'],
        'crash_discovery_rate_per_hour': value['crashDiscoveryRatePerHour'],
        'system_efficiency_score': value['systemEfficiencyScore'],
    };
}

