/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Artifact
 */
export interface Artifact {
    /**
     * Unique identifier for the artifact
     * @type {string}
     * @memberof Artifact
     */
    id: string;
    /**
     * Type of artifact
     * @type {string}
     * @memberof Artifact
     */
    type: ArtifactTypeEnum;
    /**
     * Original filename of the artifact
     * @type {string}
     * @memberof Artifact
     */
    filename: string;
    /**
     * Size of the artifact in bytes
     * @type {number}
     * @memberof Artifact
     */
    sizeBytes: number;
    /**
     * SHA256 hash of the artifact content
     * @type {string}
     * @memberof Artifact
     */
    hash: string;
    /**
     * ID of the job that generated this artifact
     * @type {string}
     * @memberof Artifact
     */
    jobId: string;
    /**
     * When the artifact was created
     * @type {Date}
     * @memberof Artifact
     */
    createdAt: Date;
    /**
     * Human-readable description of the artifact
     * @type {string}
     * @memberof Artifact
     */
    description?: string;
    /**
     * MIME type of the artifact
     * @type {string}
     * @memberof Artifact
     */
    contentType?: string;
    /**
     * URL to download the artifact
     * @type {string}
     * @memberof Artifact
     */
    downloadUrl?: string;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof Artifact
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const ArtifactTypeEnum = {
    Crash: 'crash',
    Corpus: 'corpus',
    Coverage: 'coverage',
    Log: 'log',
    Binary: 'binary',
    Config: 'config'
} as const;
export type ArtifactTypeEnum = typeof ArtifactTypeEnum[keyof typeof ArtifactTypeEnum];


/**
 * Check if a given object implements the Artifact interface.
 */
export function instanceOfArtifact(value: object): value is Artifact {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ArtifactFromJSON(json: any): Artifact {
    return ArtifactFromJSONTyped(json, false);
}

export function ArtifactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Artifact {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'filename': json['filename'],
        'sizeBytes': json['size_bytes'],
        'hash': json['hash'],
        'jobId': json['job_id'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ArtifactToJSON(json: any): Artifact {
    return ArtifactToJSONTyped(json, false);
}

export function ArtifactToJSONTyped(value?: Artifact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'filename': value['filename'],
        'size_bytes': value['sizeBytes'],
        'hash': value['hash'],
        'job_id': value['jobId'],
        'created_at': ((value['createdAt']).toISOString()),
        'description': value['description'],
        'content_type': value['contentType'],
        'download_url': value['downloadUrl'],
        'metadata': value['metadata'],
    };
}

