/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchRequestOperationsInner } from './BatchRequestOperationsInner';
import {
    BatchRequestOperationsInnerFromJSON,
    BatchRequestOperationsInnerFromJSONTyped,
    BatchRequestOperationsInnerToJSON,
    BatchRequestOperationsInnerToJSONTyped,
} from './BatchRequestOperationsInner';
import type { BatchRequestOptions } from './BatchRequestOptions';
import {
    BatchRequestOptionsFromJSON,
    BatchRequestOptionsFromJSONTyped,
    BatchRequestOptionsToJSON,
    BatchRequestOptionsToJSONTyped,
} from './BatchRequestOptions';

/**
 * 
 * @export
 * @interface BatchRequest
 */
export interface BatchRequest {
    /**
     * List of operations to execute
     * @type {Array<BatchRequestOperationsInner>}
     * @memberof BatchRequest
     */
    operations: Array<BatchRequestOperationsInner>;
    /**
     * 
     * @type {BatchRequestOptions}
     * @memberof BatchRequest
     */
    options?: BatchRequestOptions;
}

/**
 * Check if a given object implements the BatchRequest interface.
 */
export function instanceOfBatchRequest(value: object): value is BatchRequest {
    if (!('operations' in value) || value['operations'] === undefined) return false;
    return true;
}

export function BatchRequestFromJSON(json: any): BatchRequest {
    return BatchRequestFromJSONTyped(json, false);
}

export function BatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'operations': ((json['operations'] as Array<any>).map(BatchRequestOperationsInnerFromJSON)),
        'options': json['options'] == null ? undefined : BatchRequestOptionsFromJSON(json['options']),
    };
}

export function BatchRequestToJSON(json: any): BatchRequest {
    return BatchRequestToJSONTyped(json, false);
}

export function BatchRequestToJSONTyped(value?: BatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operations': ((value['operations'] as Array<any>).map(BatchRequestOperationsInnerToJSON)),
        'options': BatchRequestOptionsToJSON(value['options']),
    };
}

