/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProblemDetails } from './ProblemDetails';
import {
    ProblemDetailsFromJSON,
    ProblemDetailsFromJSONTyped,
    ProblemDetailsToJSON,
    ProblemDetailsToJSONTyped,
} from './ProblemDetails';

/**
 * 
 * @export
 * @interface BatchResponseResultsInner
 */
export interface BatchResponseResultsInner {
    /**
     * Index of the operation in the original request
     * @type {number}
     * @memberof BatchResponseResultsInner
     */
    operationIndex: number;
    /**
     * Type of operation that was executed
     * @type {string}
     * @memberof BatchResponseResultsInner
     */
    operation: string;
    /**
     * Client-provided operation ID if specified
     * @type {string}
     * @memberof BatchResponseResultsInner
     */
    operationId?: string;
    /**
     * Status of the operation
     * @type {string}
     * @memberof BatchResponseResultsInner
     */
    status: BatchResponseResultsInnerStatusEnum;
    /**
     * Operation result data (for successful operations)
     * @type {object}
     * @memberof BatchResponseResultsInner
     */
    result?: object;
    /**
     * 
     * @type {ProblemDetails}
     * @memberof BatchResponseResultsInner
     */
    error?: ProblemDetails;
    /**
     * Time taken for this operation
     * @type {number}
     * @memberof BatchResponseResultsInner
     */
    executionTimeSeconds?: number;
}


/**
 * @export
 */
export const BatchResponseResultsInnerStatusEnum = {
    Success: 'success',
    Failed: 'failed',
    Skipped: 'skipped'
} as const;
export type BatchResponseResultsInnerStatusEnum = typeof BatchResponseResultsInnerStatusEnum[keyof typeof BatchResponseResultsInnerStatusEnum];


/**
 * Check if a given object implements the BatchResponseResultsInner interface.
 */
export function instanceOfBatchResponseResultsInner(value: object): value is BatchResponseResultsInner {
    if (!('operationIndex' in value) || value['operationIndex'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BatchResponseResultsInnerFromJSON(json: any): BatchResponseResultsInner {
    return BatchResponseResultsInnerFromJSONTyped(json, false);
}

export function BatchResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'operationIndex': json['operation_index'],
        'operation': json['operation'],
        'operationId': json['operation_id'] == null ? undefined : json['operation_id'],
        'status': json['status'],
        'result': json['result'] == null ? undefined : json['result'],
        'error': json['error'] == null ? undefined : ProblemDetailsFromJSON(json['error']),
        'executionTimeSeconds': json['execution_time_seconds'] == null ? undefined : json['execution_time_seconds'],
    };
}

export function BatchResponseResultsInnerToJSON(json: any): BatchResponseResultsInner {
    return BatchResponseResultsInnerToJSONTyped(json, false);
}

export function BatchResponseResultsInnerToJSONTyped(value?: BatchResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation_index': value['operationIndex'],
        'operation': value['operation'],
        'operation_id': value['operationId'],
        'status': value['status'],
        'result': value['result'],
        'error': ProblemDetailsToJSON(value['error']),
        'execution_time_seconds': value['executionTimeSeconds'],
    };
}

