/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchRequestOperationsInner
 */
export interface BatchRequestOperationsInner {
    /**
     * Type of operation to perform
     * @type {string}
     * @memberof BatchRequestOperationsInner
     */
    operation: BatchRequestOperationsInnerOperationEnum;
    /**
     * Operation-specific data payload
     * @type {object}
     * @memberof BatchRequestOperationsInner
     */
    data: object;
    /**
     * Optional client-provided operation ID for tracking
     * @type {string}
     * @memberof BatchRequestOperationsInner
     */
    operationId?: string;
}


/**
 * @export
 */
export const BatchRequestOperationsInnerOperationEnum = {
    CreateJob: 'create_job',
    CreateCampaign: 'create_campaign',
    UploadCorpus: 'upload_corpus',
    CreateBot: 'create_bot',
    DeleteJob: 'delete_job',
    DeleteCampaign: 'delete_campaign'
} as const;
export type BatchRequestOperationsInnerOperationEnum = typeof BatchRequestOperationsInnerOperationEnum[keyof typeof BatchRequestOperationsInnerOperationEnum];


/**
 * Check if a given object implements the BatchRequestOperationsInner interface.
 */
export function instanceOfBatchRequestOperationsInner(value: object): value is BatchRequestOperationsInner {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BatchRequestOperationsInnerFromJSON(json: any): BatchRequestOperationsInner {
    return BatchRequestOperationsInnerFromJSONTyped(json, false);
}

export function BatchRequestOperationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRequestOperationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'],
        'data': json['data'],
        'operationId': json['operation_id'] == null ? undefined : json['operation_id'],
    };
}

export function BatchRequestOperationsInnerToJSON(json: any): BatchRequestOperationsInner {
    return BatchRequestOperationsInnerToJSONTyped(json, false);
}

export function BatchRequestOperationsInnerToJSONTyped(value?: BatchRequestOperationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'data': value['data'],
        'operation_id': value['operationId'],
    };
}

