/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Batch execution options
 * @export
 * @interface BatchRequestOptions
 */
export interface BatchRequestOptions {
    /**
     * Whether all operations must succeed or all fail
     * @type {boolean}
     * @memberof BatchRequestOptions
     */
    atomic?: boolean;
    /**
     * Whether to stop on first failure
     * @type {boolean}
     * @memberof BatchRequestOptions
     */
    failFast?: boolean;
    /**
     * Total timeout for batch execution
     * @type {number}
     * @memberof BatchRequestOptions
     */
    timeoutSeconds?: number;
}

/**
 * Check if a given object implements the BatchRequestOptions interface.
 */
export function instanceOfBatchRequestOptions(value: object): value is BatchRequestOptions {
    return true;
}

export function BatchRequestOptionsFromJSON(json: any): BatchRequestOptions {
    return BatchRequestOptionsFromJSONTyped(json, false);
}

export function BatchRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'atomic': json['atomic'] == null ? undefined : json['atomic'],
        'failFast': json['fail_fast'] == null ? undefined : json['fail_fast'],
        'timeoutSeconds': json['timeout_seconds'] == null ? undefined : json['timeout_seconds'],
    };
}

export function BatchRequestOptionsToJSON(json: any): BatchRequestOptions {
    return BatchRequestOptionsToJSONTyped(json, false);
}

export function BatchRequestOptionsToJSONTyped(value?: BatchRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atomic': value['atomic'],
        'fail_fast': value['failFast'],
        'timeout_seconds': value['timeoutSeconds'],
    };
}

