/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotStatus } from './BotStatus';
import {
    BotStatusFromJSON,
    BotStatusFromJSONTyped,
    BotStatusToJSON,
    BotStatusToJSONTyped,
} from './BotStatus';
import type { BotResourceUsage } from './BotResourceUsage';
import {
    BotResourceUsageFromJSON,
    BotResourceUsageFromJSONTyped,
    BotResourceUsageToJSON,
    BotResourceUsageToJSONTyped,
} from './BotResourceUsage';

/**
 * 
 * @export
 * @interface Bot
 */
export interface Bot {
    /**
     * Unique identifier for the bot
     * @type {string}
     * @memberof Bot
     */
    id: string;
    /**
     * Human-readable name for the bot
     * @type {string}
     * @memberof Bot
     */
    name: string;
    /**
     * Hostname where the bot is running
     * @type {string}
     * @memberof Bot
     */
    hostname: string;
    /**
     * 
     * @type {BotStatus}
     * @memberof Bot
     */
    status: BotStatus;
    /**
     * Capabilities supported by this bot
     * @type {Set<string>}
     * @memberof Bot
     */
    capabilities: Set<BotCapabilitiesEnum>;
    /**
     * Timestamp of last heartbeat received
     * @type {Date}
     * @memberof Bot
     */
    lastHeartbeat: Date;
    /**
     * Whether the bot is currently online
     * @type {boolean}
     * @memberof Bot
     */
    isOnline: boolean;
    /**
     * ID of currently assigned job, if any
     * @type {string}
     * @memberof Bot
     */
    currentJobId?: string | null;
    /**
     * When the bot was first registered
     * @type {Date}
     * @memberof Bot
     */
    registeredAt: Date;
    /**
     * API endpoint for communicating with the bot
     * @type {string}
     * @memberof Bot
     */
    apiEndpoint?: string;
    /**
     * 
     * @type {BotResourceUsage}
     * @memberof Bot
     */
    resourceUsage?: BotResourceUsage;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof Bot
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const BotCapabilitiesEnum = {
    Fuzzing: 'fuzzing',
    Analysis: 'analysis',
    Minimization: 'minimization',
    Reproduction: 'reproduction',
    Coverage: 'coverage'
} as const;
export type BotCapabilitiesEnum = typeof BotCapabilitiesEnum[keyof typeof BotCapabilitiesEnum];


/**
 * Check if a given object implements the Bot interface.
 */
export function instanceOfBot(value: object): value is Bot {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('lastHeartbeat' in value) || value['lastHeartbeat'] === undefined) return false;
    if (!('isOnline' in value) || value['isOnline'] === undefined) return false;
    if (!('registeredAt' in value) || value['registeredAt'] === undefined) return false;
    return true;
}

export function BotFromJSON(json: any): Bot {
    return BotFromJSONTyped(json, false);
}

export function BotFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bot {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'hostname': json['hostname'],
        'status': BotStatusFromJSON(json['status']),
        'capabilities': new Set(json['capabilities']),
        'lastHeartbeat': (new Date(json['last_heartbeat'])),
        'isOnline': json['is_online'],
        'currentJobId': json['current_job_id'] == null ? undefined : json['current_job_id'],
        'registeredAt': (new Date(json['registered_at'])),
        'apiEndpoint': json['api_endpoint'] == null ? undefined : json['api_endpoint'],
        'resourceUsage': json['resource_usage'] == null ? undefined : BotResourceUsageFromJSON(json['resource_usage']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function BotToJSON(json: any): Bot {
    return BotToJSONTyped(json, false);
}

export function BotToJSONTyped(value?: Bot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'hostname': value['hostname'],
        'status': BotStatusToJSON(value['status']),
        'capabilities': Array.from(value['capabilities'] as Set<any>),
        'last_heartbeat': ((value['lastHeartbeat']).toISOString()),
        'is_online': value['isOnline'],
        'current_job_id': value['currentJobId'],
        'registered_at': ((value['registeredAt']).toISOString()),
        'api_endpoint': value['apiEndpoint'],
        'resource_usage': BotResourceUsageToJSON(value['resourceUsage']),
        'metadata': value['metadata'],
    };
}

