/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotCreateRequest
 */
export interface BotCreateRequest {
    /**
     * Human-readable name for the bot
     * @type {string}
     * @memberof BotCreateRequest
     */
    name: string;
    /**
     * Hostname where the bot is running
     * @type {string}
     * @memberof BotCreateRequest
     */
    hostname: string;
    /**
     * Capabilities supported by this bot
     * @type {Set<string>}
     * @memberof BotCreateRequest
     */
    capabilities: Set<BotCreateRequestCapabilitiesEnum>;
    /**
     * API endpoint for communicating with the bot
     * @type {string}
     * @memberof BotCreateRequest
     */
    apiEndpoint: string;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof BotCreateRequest
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const BotCreateRequestCapabilitiesEnum = {
    Fuzzing: 'fuzzing',
    Analysis: 'analysis',
    Minimization: 'minimization',
    Reproduction: 'reproduction',
    Coverage: 'coverage'
} as const;
export type BotCreateRequestCapabilitiesEnum = typeof BotCreateRequestCapabilitiesEnum[keyof typeof BotCreateRequestCapabilitiesEnum];


/**
 * Check if a given object implements the BotCreateRequest interface.
 */
export function instanceOfBotCreateRequest(value: object): value is BotCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    if (!('apiEndpoint' in value) || value['apiEndpoint'] === undefined) return false;
    return true;
}

export function BotCreateRequestFromJSON(json: any): BotCreateRequest {
    return BotCreateRequestFromJSONTyped(json, false);
}

export function BotCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'hostname': json['hostname'],
        'capabilities': new Set(json['capabilities']),
        'apiEndpoint': json['api_endpoint'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function BotCreateRequestToJSON(json: any): BotCreateRequest {
    return BotCreateRequestToJSONTyped(json, false);
}

export function BotCreateRequestToJSONTyped(value?: BotCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'hostname': value['hostname'],
        'capabilities': Array.from(value['capabilities'] as Set<any>),
        'api_endpoint': value['apiEndpoint'],
        'metadata': value['metadata'],
    };
}

