/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotHeartbeatRequestResourceUsage } from './BotHeartbeatRequestResourceUsage';
import {
    BotHeartbeatRequestResourceUsageFromJSON,
    BotHeartbeatRequestResourceUsageFromJSONTyped,
    BotHeartbeatRequestResourceUsageToJSON,
    BotHeartbeatRequestResourceUsageToJSONTyped,
} from './BotHeartbeatRequestResourceUsage';
import type { BotStatus } from './BotStatus';
import {
    BotStatusFromJSON,
    BotStatusFromJSONTyped,
    BotStatusToJSON,
    BotStatusToJSONTyped,
} from './BotStatus';

/**
 * 
 * @export
 * @interface BotHeartbeatRequest
 */
export interface BotHeartbeatRequest {
    /**
     * 
     * @type {BotStatus}
     * @memberof BotHeartbeatRequest
     */
    status: BotStatus;
    /**
     * ID of currently assigned job, if any
     * @type {string}
     * @memberof BotHeartbeatRequest
     */
    currentJobId?: string | null;
    /**
     * 
     * @type {BotHeartbeatRequestResourceUsage}
     * @memberof BotHeartbeatRequest
     */
    resourceUsage?: BotHeartbeatRequestResourceUsage;
    /**
     * Optional status message
     * @type {string}
     * @memberof BotHeartbeatRequest
     */
    message?: string;
}



/**
 * Check if a given object implements the BotHeartbeatRequest interface.
 */
export function instanceOfBotHeartbeatRequest(value: object): value is BotHeartbeatRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BotHeartbeatRequestFromJSON(json: any): BotHeartbeatRequest {
    return BotHeartbeatRequestFromJSONTyped(json, false);
}

export function BotHeartbeatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotHeartbeatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': BotStatusFromJSON(json['status']),
        'currentJobId': json['current_job_id'] == null ? undefined : json['current_job_id'],
        'resourceUsage': json['resource_usage'] == null ? undefined : BotHeartbeatRequestResourceUsageFromJSON(json['resource_usage']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function BotHeartbeatRequestToJSON(json: any): BotHeartbeatRequest {
    return BotHeartbeatRequestToJSONTyped(json, false);
}

export function BotHeartbeatRequestToJSONTyped(value?: BotHeartbeatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': BotStatusToJSON(value['status']),
        'current_job_id': value['currentJobId'],
        'resource_usage': BotHeartbeatRequestResourceUsageToJSON(value['resourceUsage']),
        'message': value['message'],
    };
}

