/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BotHeartbeatResponseCommandsInner } from './BotHeartbeatResponseCommandsInner';
import {
    BotHeartbeatResponseCommandsInnerFromJSON,
    BotHeartbeatResponseCommandsInnerFromJSONTyped,
    BotHeartbeatResponseCommandsInnerToJSON,
    BotHeartbeatResponseCommandsInnerToJSONTyped,
} from './BotHeartbeatResponseCommandsInner';

/**
 * 
 * @export
 * @interface BotHeartbeatResponse
 */
export interface BotHeartbeatResponse {
    /**
     * Whether the heartbeat was acknowledged
     * @type {boolean}
     * @memberof BotHeartbeatResponse
     */
    acknowledged: boolean;
    /**
     * Interval for next heartbeat in seconds
     * @type {number}
     * @memberof BotHeartbeatResponse
     */
    nextHeartbeatIntervalSeconds: number;
    /**
     * ID of newly assigned job, if any
     * @type {string}
     * @memberof BotHeartbeatResponse
     */
    assignedJobId?: string | null;
    /**
     * Commands for the bot to execute
     * @type {Array<BotHeartbeatResponseCommandsInner>}
     * @memberof BotHeartbeatResponse
     */
    commands?: Array<BotHeartbeatResponseCommandsInner>;
    /**
     * Optional message from the master
     * @type {string}
     * @memberof BotHeartbeatResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the BotHeartbeatResponse interface.
 */
export function instanceOfBotHeartbeatResponse(value: object): value is BotHeartbeatResponse {
    if (!('acknowledged' in value) || value['acknowledged'] === undefined) return false;
    if (!('nextHeartbeatIntervalSeconds' in value) || value['nextHeartbeatIntervalSeconds'] === undefined) return false;
    return true;
}

export function BotHeartbeatResponseFromJSON(json: any): BotHeartbeatResponse {
    return BotHeartbeatResponseFromJSONTyped(json, false);
}

export function BotHeartbeatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotHeartbeatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'acknowledged': json['acknowledged'],
        'nextHeartbeatIntervalSeconds': json['next_heartbeat_interval_seconds'],
        'assignedJobId': json['assigned_job_id'] == null ? undefined : json['assigned_job_id'],
        'commands': json['commands'] == null ? undefined : ((json['commands'] as Array<any>).map(BotHeartbeatResponseCommandsInnerFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function BotHeartbeatResponseToJSON(json: any): BotHeartbeatResponse {
    return BotHeartbeatResponseToJSONTyped(json, false);
}

export function BotHeartbeatResponseToJSONTyped(value?: BotHeartbeatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acknowledged': value['acknowledged'],
        'next_heartbeat_interval_seconds': value['nextHeartbeatIntervalSeconds'],
        'assigned_job_id': value['assignedJobId'],
        'commands': value['commands'] == null ? undefined : ((value['commands'] as Array<any>).map(BotHeartbeatResponseCommandsInnerToJSON)),
        'message': value['message'],
    };
}

