/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotHeartbeatResponseCommandsInner
 */
export interface BotHeartbeatResponseCommandsInner {
    /**
     * 
     * @type {string}
     * @memberof BotHeartbeatResponseCommandsInner
     */
    type?: BotHeartbeatResponseCommandsInnerTypeEnum;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BotHeartbeatResponseCommandsInner
     */
    parameters?: { [key: string]: any; };
}


/**
 * @export
 */
export const BotHeartbeatResponseCommandsInnerTypeEnum = {
    StopJob: 'stop_job',
    UpdateConfig: 'update_config',
    Restart: 'restart',
    Maintenance: 'maintenance'
} as const;
export type BotHeartbeatResponseCommandsInnerTypeEnum = typeof BotHeartbeatResponseCommandsInnerTypeEnum[keyof typeof BotHeartbeatResponseCommandsInnerTypeEnum];


/**
 * Check if a given object implements the BotHeartbeatResponseCommandsInner interface.
 */
export function instanceOfBotHeartbeatResponseCommandsInner(value: object): value is BotHeartbeatResponseCommandsInner {
    return true;
}

export function BotHeartbeatResponseCommandsInnerFromJSON(json: any): BotHeartbeatResponseCommandsInner {
    return BotHeartbeatResponseCommandsInnerFromJSONTyped(json, false);
}

export function BotHeartbeatResponseCommandsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotHeartbeatResponseCommandsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'parameters': json['parameters'] == null ? undefined : json['parameters'],
    };
}

export function BotHeartbeatResponseCommandsInnerToJSON(json: any): BotHeartbeatResponseCommandsInner {
    return BotHeartbeatResponseCommandsInnerToJSONTyped(json, false);
}

export function BotHeartbeatResponseCommandsInnerToJSONTyped(value?: BotHeartbeatResponseCommandsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'parameters': value['parameters'],
    };
}

