/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BotUpdateRequest
 */
export interface BotUpdateRequest {
    /**
     * Human-readable name for the bot
     * @type {string}
     * @memberof BotUpdateRequest
     */
    name?: string;
    /**
     * Capabilities supported by this bot
     * @type {Set<string>}
     * @memberof BotUpdateRequest
     */
    capabilities?: Set<BotUpdateRequestCapabilitiesEnum>;
    /**
     * API endpoint for communicating with the bot
     * @type {string}
     * @memberof BotUpdateRequest
     */
    apiEndpoint?: string;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof BotUpdateRequest
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const BotUpdateRequestCapabilitiesEnum = {
    Fuzzing: 'fuzzing',
    Analysis: 'analysis',
    Minimization: 'minimization',
    Reproduction: 'reproduction',
    Coverage: 'coverage'
} as const;
export type BotUpdateRequestCapabilitiesEnum = typeof BotUpdateRequestCapabilitiesEnum[keyof typeof BotUpdateRequestCapabilitiesEnum];


/**
 * Check if a given object implements the BotUpdateRequest interface.
 */
export function instanceOfBotUpdateRequest(value: object): value is BotUpdateRequest {
    return true;
}

export function BotUpdateRequestFromJSON(json: any): BotUpdateRequest {
    return BotUpdateRequestFromJSONTyped(json, false);
}

export function BotUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BotUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'capabilities': json['capabilities'] == null ? undefined : new Set(json['capabilities']),
        'apiEndpoint': json['api_endpoint'] == null ? undefined : json['api_endpoint'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function BotUpdateRequestToJSON(json: any): BotUpdateRequest {
    return BotUpdateRequestToJSONTyped(json, false);
}

export function BotUpdateRequestToJSONTyped(value?: BotUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'capabilities': value['capabilities'] == null ? undefined : Array.from(value['capabilities'] as Set<any>),
        'api_endpoint': value['apiEndpoint'],
        'metadata': value['metadata'],
    };
}

