/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignStatsPerformanceMetrics } from './CampaignStatsPerformanceMetrics';
import {
    CampaignStatsPerformanceMetricsFromJSON,
    CampaignStatsPerformanceMetricsFromJSONTyped,
    CampaignStatsPerformanceMetricsToJSON,
    CampaignStatsPerformanceMetricsToJSONTyped,
} from './CampaignStatsPerformanceMetrics';

/**
 * 
 * @export
 * @interface CampaignStats
 */
export interface CampaignStats {
    /**
     * ID of the campaign
     * @type {string}
     * @memberof CampaignStats
     */
    campaignId: string;
    /**
     * Total number of jobs in the campaign
     * @type {number}
     * @memberof CampaignStats
     */
    totalJobs: number;
    /**
     * Number of currently running jobs
     * @type {number}
     * @memberof CampaignStats
     */
    activeJobs: number;
    /**
     * Number of completed jobs
     * @type {number}
     * @memberof CampaignStats
     */
    completedJobs: number;
    /**
     * Number of failed jobs
     * @type {number}
     * @memberof CampaignStats
     */
    failedJobs: number;
    /**
     * Total number of crashes found
     * @type {number}
     * @memberof CampaignStats
     */
    totalCrashes: number;
    /**
     * Number of unique crashes
     * @type {number}
     * @memberof CampaignStats
     */
    uniqueCrashes: number;
    /**
     * Total number of corpus entries
     * @type {number}
     * @memberof CampaignStats
     */
    corpusSize: number;
    /**
     * Total corpus size in bytes
     * @type {number}
     * @memberof CampaignStats
     */
    corpusSizeBytes?: number;
    /**
     * Total coverage edges discovered
     * @type {number}
     * @memberof CampaignStats
     */
    totalCoverageEdges: number;
    /**
     * Total execution time across all jobs
     * @type {number}
     * @memberof CampaignStats
     */
    executionTimeSeconds: number;
    /**
     * When the statistics were last updated
     * @type {Date}
     * @memberof CampaignStats
     */
    lastUpdated: Date;
    /**
     * 
     * @type {CampaignStatsPerformanceMetrics}
     * @memberof CampaignStats
     */
    performanceMetrics?: CampaignStatsPerformanceMetrics;
}

/**
 * Check if a given object implements the CampaignStats interface.
 */
export function instanceOfCampaignStats(value: object): value is CampaignStats {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('totalJobs' in value) || value['totalJobs'] === undefined) return false;
    if (!('activeJobs' in value) || value['activeJobs'] === undefined) return false;
    if (!('completedJobs' in value) || value['completedJobs'] === undefined) return false;
    if (!('failedJobs' in value) || value['failedJobs'] === undefined) return false;
    if (!('totalCrashes' in value) || value['totalCrashes'] === undefined) return false;
    if (!('uniqueCrashes' in value) || value['uniqueCrashes'] === undefined) return false;
    if (!('corpusSize' in value) || value['corpusSize'] === undefined) return false;
    if (!('totalCoverageEdges' in value) || value['totalCoverageEdges'] === undefined) return false;
    if (!('executionTimeSeconds' in value) || value['executionTimeSeconds'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function CampaignStatsFromJSON(json: any): CampaignStats {
    return CampaignStatsFromJSONTyped(json, false);
}

export function CampaignStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignStats {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'],
        'totalJobs': json['total_jobs'],
        'activeJobs': json['active_jobs'],
        'completedJobs': json['completed_jobs'],
        'failedJobs': json['failed_jobs'],
        'totalCrashes': json['total_crashes'],
        'uniqueCrashes': json['unique_crashes'],
        'corpusSize': json['corpus_size'],
        'corpusSizeBytes': json['corpus_size_bytes'] == null ? undefined : json['corpus_size_bytes'],
        'totalCoverageEdges': json['total_coverage_edges'],
        'executionTimeSeconds': json['execution_time_seconds'],
        'lastUpdated': (new Date(json['last_updated'])),
        'performanceMetrics': json['performance_metrics'] == null ? undefined : CampaignStatsPerformanceMetricsFromJSON(json['performance_metrics']),
    };
}

export function CampaignStatsToJSON(json: any): CampaignStats {
    return CampaignStatsToJSONTyped(json, false);
}

export function CampaignStatsToJSONTyped(value?: CampaignStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'total_jobs': value['totalJobs'],
        'active_jobs': value['activeJobs'],
        'completed_jobs': value['completedJobs'],
        'failed_jobs': value['failedJobs'],
        'total_crashes': value['totalCrashes'],
        'unique_crashes': value['uniqueCrashes'],
        'corpus_size': value['corpusSize'],
        'corpus_size_bytes': value['corpusSizeBytes'],
        'total_coverage_edges': value['totalCoverageEdges'],
        'execution_time_seconds': value['executionTimeSeconds'],
        'last_updated': ((value['lastUpdated']).toISOString()),
        'performance_metrics': CampaignStatsPerformanceMetricsToJSON(value['performanceMetrics']),
    };
}

