/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current status of a campaign
 * @export
 */
export const CampaignStatus = {
    Draft: 'draft',
    Active: 'active',
    Paused: 'paused',
    Completed: 'completed',
    Cancelled: 'cancelled',
    Archived: 'archived'
} as const;
export type CampaignStatus = typeof CampaignStatus[keyof typeof CampaignStatus];


export function instanceOfCampaignStatus(value: any): boolean {
    for (const key in CampaignStatus) {
        if (Object.prototype.hasOwnProperty.call(CampaignStatus, key)) {
            if (CampaignStatus[key as keyof typeof CampaignStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CampaignStatusFromJSON(json: any): CampaignStatus {
    return CampaignStatusFromJSONTyped(json, false);
}

export function CampaignStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignStatus {
    return json as CampaignStatus;
}

export function CampaignStatusToJSON(value?: CampaignStatus | null): any {
    return value as any;
}

export function CampaignStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CampaignStatus {
    return value as CampaignStatus;
}

