/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignCreateRequestJobTemplate } from './CampaignCreateRequestJobTemplate';
import {
    CampaignCreateRequestJobTemplateFromJSON,
    CampaignCreateRequestJobTemplateFromJSONTyped,
    CampaignCreateRequestJobTemplateToJSON,
    CampaignCreateRequestJobTemplateToJSONTyped,
} from './CampaignCreateRequestJobTemplate';

/**
 * 
 * @export
 * @interface CampaignCreateRequest
 */
export interface CampaignCreateRequest {
    /**
     * Human-readable name for the campaign
     * @type {string}
     * @memberof CampaignCreateRequest
     */
    name: string;
    /**
     * Detailed description of the campaign
     * @type {string}
     * @memberof CampaignCreateRequest
     */
    description?: string;
    /**
     * Path to the target binary
     * @type {string}
     * @memberof CampaignCreateRequest
     */
    targetBinary: string;
    /**
     * Maximum campaign duration in seconds
     * @type {number}
     * @memberof CampaignCreateRequest
     */
    maxDurationSeconds?: number;
    /**
     * Maximum number of concurrent jobs
     * @type {number}
     * @memberof CampaignCreateRequest
     */
    maxJobs?: number;
    /**
     * 
     * @type {CampaignCreateRequestJobTemplate}
     * @memberof CampaignCreateRequest
     */
    jobTemplate?: CampaignCreateRequestJobTemplate;
    /**
     * Whether to automatically restart failed jobs
     * @type {boolean}
     * @memberof CampaignCreateRequest
     */
    autoRestart?: boolean;
    /**
     * Whether to share corpus between jobs in this campaign
     * @type {boolean}
     * @memberof CampaignCreateRequest
     */
    sharedCorpus?: boolean;
    /**
     * Tags for categorizing and filtering campaigns
     * @type {Set<string>}
     * @memberof CampaignCreateRequest
     */
    tags?: Set<string>;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof CampaignCreateRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CampaignCreateRequest interface.
 */
export function instanceOfCampaignCreateRequest(value: object): value is CampaignCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('targetBinary' in value) || value['targetBinary'] === undefined) return false;
    return true;
}

export function CampaignCreateRequestFromJSON(json: any): CampaignCreateRequest {
    return CampaignCreateRequestFromJSONTyped(json, false);
}

export function CampaignCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'targetBinary': json['target_binary'],
        'maxDurationSeconds': json['max_duration_seconds'] == null ? undefined : json['max_duration_seconds'],
        'maxJobs': json['max_jobs'] == null ? undefined : json['max_jobs'],
        'jobTemplate': json['job_template'] == null ? undefined : CampaignCreateRequestJobTemplateFromJSON(json['job_template']),
        'autoRestart': json['auto_restart'] == null ? undefined : json['auto_restart'],
        'sharedCorpus': json['shared_corpus'] == null ? undefined : json['shared_corpus'],
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CampaignCreateRequestToJSON(json: any): CampaignCreateRequest {
    return CampaignCreateRequestToJSONTyped(json, false);
}

export function CampaignCreateRequestToJSONTyped(value?: CampaignCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'target_binary': value['targetBinary'],
        'max_duration_seconds': value['maxDurationSeconds'],
        'max_jobs': value['maxJobs'],
        'job_template': CampaignCreateRequestJobTemplateToJSON(value['jobTemplate']),
        'auto_restart': value['autoRestart'],
        'shared_corpus': value['sharedCorpus'],
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
        'metadata': value['metadata'],
    };
}

