/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverageFormat } from './CoverageFormat';
import {
    CoverageFormatFromJSON,
    CoverageFormatFromJSONTyped,
    CoverageFormatToJSON,
    CoverageFormatToJSONTyped,
} from './CoverageFormat';
import type { FuzzerType } from './FuzzerType';
import {
    FuzzerTypeFromJSON,
    FuzzerTypeFromJSONTyped,
    FuzzerTypeToJSON,
    FuzzerTypeToJSONTyped,
} from './FuzzerType';

/**
 * Template for jobs created in this campaign
 * @export
 * @interface CampaignJobTemplate
 */
export interface CampaignJobTemplate {
    /**
     * 
     * @type {FuzzerType}
     * @memberof CampaignJobTemplate
     */
    fuzzer?: FuzzerType;
    /**
     * 
     * @type {number}
     * @memberof CampaignJobTemplate
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CampaignJobTemplate
     */
    config?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CampaignJobTemplate
     */
    enableCoverage?: boolean;
    /**
     * 
     * @type {CoverageFormat}
     * @memberof CampaignJobTemplate
     */
    coverageFormat?: CoverageFormat;
}



/**
 * Check if a given object implements the CampaignJobTemplate interface.
 */
export function instanceOfCampaignJobTemplate(value: object): value is CampaignJobTemplate {
    return true;
}

export function CampaignJobTemplateFromJSON(json: any): CampaignJobTemplate {
    return CampaignJobTemplateFromJSONTyped(json, false);
}

export function CampaignJobTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignJobTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'fuzzer': json['fuzzer'] == null ? undefined : FuzzerTypeFromJSON(json['fuzzer']),
        'timeoutSeconds': json['timeout_seconds'] == null ? undefined : json['timeout_seconds'],
        'config': json['config'] == null ? undefined : json['config'],
        'enableCoverage': json['enable_coverage'] == null ? undefined : json['enable_coverage'],
        'coverageFormat': json['coverage_format'] == null ? undefined : CoverageFormatFromJSON(json['coverage_format']),
    };
}

export function CampaignJobTemplateToJSON(json: any): CampaignJobTemplate {
    return CampaignJobTemplateToJSONTyped(json, false);
}

export function CampaignJobTemplateToJSONTyped(value?: CampaignJobTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fuzzer': FuzzerTypeToJSON(value['fuzzer']),
        'timeout_seconds': value['timeoutSeconds'],
        'config': value['config'],
        'enable_coverage': value['enableCoverage'],
        'coverage_format': CoverageFormatToJSON(value['coverageFormat']),
    };
}

