/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Performance and efficiency metrics
 * @export
 * @interface CampaignStatsPerformanceMetrics
 */
export interface CampaignStatsPerformanceMetrics {
    /**
     * Average executions per second
     * @type {number}
     * @memberof CampaignStatsPerformanceMetrics
     */
    avgExecutionsPerSecond?: number;
    /**
     * Rate of coverage growth per hour
     * @type {number}
     * @memberof CampaignStatsPerformanceMetrics
     */
    coverageGrowthRate?: number;
    /**
     * Rate of crash discovery per hour
     * @type {number}
     * @memberof CampaignStatsPerformanceMetrics
     */
    crashDiscoveryRate?: number;
}

/**
 * Check if a given object implements the CampaignStatsPerformanceMetrics interface.
 */
export function instanceOfCampaignStatsPerformanceMetrics(value: object): value is CampaignStatsPerformanceMetrics {
    return true;
}

export function CampaignStatsPerformanceMetricsFromJSON(json: any): CampaignStatsPerformanceMetrics {
    return CampaignStatsPerformanceMetricsFromJSONTyped(json, false);
}

export function CampaignStatsPerformanceMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignStatsPerformanceMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'avgExecutionsPerSecond': json['avg_executions_per_second'] == null ? undefined : json['avg_executions_per_second'],
        'coverageGrowthRate': json['coverage_growth_rate'] == null ? undefined : json['coverage_growth_rate'],
        'crashDiscoveryRate': json['crash_discovery_rate'] == null ? undefined : json['crash_discovery_rate'],
    };
}

export function CampaignStatsPerformanceMetricsToJSON(json: any): CampaignStatsPerformanceMetrics {
    return CampaignStatsPerformanceMetricsToJSONTyped(json, false);
}

export function CampaignStatsPerformanceMetricsToJSONTyped(value?: CampaignStatsPerformanceMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_executions_per_second': value['avgExecutionsPerSecond'],
        'coverage_growth_rate': value['coverageGrowthRate'],
        'crash_discovery_rate': value['crashDiscoveryRate'],
    };
}

