/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Coverage information for this corpus entry
 * @export
 * @interface CorpusEntryCoverageInfo
 */
export interface CorpusEntryCoverageInfo {
    /**
     * Number of coverage edges this input covers
     * @type {number}
     * @memberof CorpusEntryCoverageInfo
     */
    edgesCovered?: number;
    /**
     * Number of new edges discovered by this input
     * @type {number}
     * @memberof CorpusEntryCoverageInfo
     */
    newEdges?: number;
    /**
     * Number of basic blocks covered
     * @type {number}
     * @memberof CorpusEntryCoverageInfo
     */
    blocksCovered?: number;
}

/**
 * Check if a given object implements the CorpusEntryCoverageInfo interface.
 */
export function instanceOfCorpusEntryCoverageInfo(value: object): value is CorpusEntryCoverageInfo {
    return true;
}

export function CorpusEntryCoverageInfoFromJSON(json: any): CorpusEntryCoverageInfo {
    return CorpusEntryCoverageInfoFromJSONTyped(json, false);
}

export function CorpusEntryCoverageInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusEntryCoverageInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'edgesCovered': json['edges_covered'] == null ? undefined : json['edges_covered'],
        'newEdges': json['new_edges'] == null ? undefined : json['new_edges'],
        'blocksCovered': json['blocks_covered'] == null ? undefined : json['blocks_covered'],
    };
}

export function CorpusEntryCoverageInfoToJSON(json: any): CorpusEntryCoverageInfo {
    return CorpusEntryCoverageInfoToJSONTyped(json, false);
}

export function CorpusEntryCoverageInfoToJSONTyped(value?: CorpusEntryCoverageInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges_covered': value['edgesCovered'],
        'new_edges': value['newEdges'],
        'blocks_covered': value['blocksCovered'],
    };
}

