/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusEntryCoverageInfo } from './CorpusEntryCoverageInfo';
import {
    CorpusEntryCoverageInfoFromJSON,
    CorpusEntryCoverageInfoFromJSONTyped,
    CorpusEntryCoverageInfoToJSON,
    CorpusEntryCoverageInfoToJSONTyped,
} from './CorpusEntryCoverageInfo';
import type { CorpusEntryGenerationInfo } from './CorpusEntryGenerationInfo';
import {
    CorpusEntryGenerationInfoFromJSON,
    CorpusEntryGenerationInfoFromJSONTyped,
    CorpusEntryGenerationInfoToJSON,
    CorpusEntryGenerationInfoToJSONTyped,
} from './CorpusEntryGenerationInfo';

/**
 * 
 * @export
 * @interface CorpusEntry
 */
export interface CorpusEntry {
    /**
     * Unique identifier for the corpus entry
     * @type {string}
     * @memberof CorpusEntry
     */
    id: string;
    /**
     * Original filename of the corpus file
     * @type {string}
     * @memberof CorpusEntry
     */
    filename: string;
    /**
     * Size of the corpus file in bytes
     * @type {number}
     * @memberof CorpusEntry
     */
    sizeBytes: number;
    /**
     * SHA256 hash of the corpus file content
     * @type {string}
     * @memberof CorpusEntry
     */
    hash: string;
    /**
     * ID of the campaign this corpus belongs to
     * @type {string}
     * @memberof CorpusEntry
     */
    campaignId: string;
    /**
     * ID of the job that generated this corpus
     * @type {string}
     * @memberof CorpusEntry
     */
    jobId: string;
    /**
     * ID of the bot that generated this corpus
     * @type {string}
     * @memberof CorpusEntry
     */
    botId?: string;
    /**
     * When the corpus entry was created
     * @type {Date}
     * @memberof CorpusEntry
     */
    createdAt: Date;
    /**
     * 
     * @type {CorpusEntryCoverageInfo}
     * @memberof CorpusEntry
     */
    coverageInfo?: CorpusEntryCoverageInfo;
    /**
     * 
     * @type {CorpusEntryGenerationInfo}
     * @memberof CorpusEntry
     */
    generationInfo?: CorpusEntryGenerationInfo;
    /**
     * Whether this is an initial seed corpus entry
     * @type {boolean}
     * @memberof CorpusEntry
     */
    isSeed?: boolean;
    /**
     * Whether this corpus has been minimized
     * @type {boolean}
     * @memberof CorpusEntry
     */
    isMinimized?: boolean;
    /**
     * Tags associated with this corpus entry
     * @type {Set<string>}
     * @memberof CorpusEntry
     */
    tags?: Set<string>;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof CorpusEntry
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CorpusEntry interface.
 */
export function instanceOfCorpusEntry(value: object): value is CorpusEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CorpusEntryFromJSON(json: any): CorpusEntry {
    return CorpusEntryFromJSONTyped(json, false);
}

export function CorpusEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'filename': json['filename'],
        'sizeBytes': json['size_bytes'],
        'hash': json['hash'],
        'campaignId': json['campaign_id'],
        'jobId': json['job_id'],
        'botId': json['bot_id'] == null ? undefined : json['bot_id'],
        'createdAt': (new Date(json['created_at'])),
        'coverageInfo': json['coverage_info'] == null ? undefined : CorpusEntryCoverageInfoFromJSON(json['coverage_info']),
        'generationInfo': json['generation_info'] == null ? undefined : CorpusEntryGenerationInfoFromJSON(json['generation_info']),
        'isSeed': json['is_seed'] == null ? undefined : json['is_seed'],
        'isMinimized': json['is_minimized'] == null ? undefined : json['is_minimized'],
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CorpusEntryToJSON(json: any): CorpusEntry {
    return CorpusEntryToJSONTyped(json, false);
}

export function CorpusEntryToJSONTyped(value?: CorpusEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'filename': value['filename'],
        'size_bytes': value['sizeBytes'],
        'hash': value['hash'],
        'campaign_id': value['campaignId'],
        'job_id': value['jobId'],
        'bot_id': value['botId'],
        'created_at': ((value['createdAt']).toISOString()),
        'coverage_info': CorpusEntryCoverageInfoToJSON(value['coverageInfo']),
        'generation_info': CorpusEntryGenerationInfoToJSON(value['generationInfo']),
        'is_seed': value['isSeed'],
        'is_minimized': value['isMinimized'],
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
        'metadata': value['metadata'],
    };
}

