/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Quality metrics of the selection
 * @export
 * @interface CorpusSelectionResponseQualityMetrics
 */
export interface CorpusSelectionResponseQualityMetrics {
    /**
     * Coverage per byte ratio
     * @type {number}
     * @memberof CorpusSelectionResponseQualityMetrics
     */
    coverageDensity?: number;
    /**
     * Diversity score of selected corpus
     * @type {number}
     * @memberof CorpusSelectionResponseQualityMetrics
     */
    diversityScore?: number;
    /**
     * Redundancy score (lower is better)
     * @type {number}
     * @memberof CorpusSelectionResponseQualityMetrics
     */
    redundancyScore?: number;
}

/**
 * Check if a given object implements the CorpusSelectionResponseQualityMetrics interface.
 */
export function instanceOfCorpusSelectionResponseQualityMetrics(value: object): value is CorpusSelectionResponseQualityMetrics {
    return true;
}

export function CorpusSelectionResponseQualityMetricsFromJSON(json: any): CorpusSelectionResponseQualityMetrics {
    return CorpusSelectionResponseQualityMetricsFromJSONTyped(json, false);
}

export function CorpusSelectionResponseQualityMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSelectionResponseQualityMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'coverageDensity': json['coverage_density'] == null ? undefined : json['coverage_density'],
        'diversityScore': json['diversity_score'] == null ? undefined : json['diversity_score'],
        'redundancyScore': json['redundancy_score'] == null ? undefined : json['redundancy_score'],
    };
}

export function CorpusSelectionResponseQualityMetricsToJSON(json: any): CorpusSelectionResponseQualityMetrics {
    return CorpusSelectionResponseQualityMetricsToJSONTyped(json, false);
}

export function CorpusSelectionResponseQualityMetricsToJSONTyped(value?: CorpusSelectionResponseQualityMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coverage_density': value['coverageDensity'],
        'diversity_score': value['diversityScore'],
        'redundancy_score': value['redundancyScore'],
    };
}

