/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { CorpusEntry } from './CorpusEntry';
import {
    CorpusEntryFromJSON,
    CorpusEntryFromJSONTyped,
    CorpusEntryToJSON,
    CorpusEntryToJSONTyped,
} from './CorpusEntry';

/**
 * 
 * @export
 * @interface CorpusListResponse
 */
export interface CorpusListResponse {
    /**
     * 
     * @type {Array<CorpusEntry>}
     * @memberof CorpusListResponse
     */
    data: Array<CorpusEntry>;
    /**
     * 
     * @type {Pagination}
     * @memberof CorpusListResponse
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the CorpusListResponse interface.
 */
export function instanceOfCorpusListResponse(value: object): value is CorpusListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function CorpusListResponseFromJSON(json: any): CorpusListResponse {
    return CorpusListResponseFromJSONTyped(json, false);
}

export function CorpusListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CorpusEntryFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function CorpusListResponseToJSON(json: any): CorpusListResponse {
    return CorpusListResponseToJSONTyped(json, false);
}

export function CorpusListResponseToJSONTyped(value?: CorpusListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CorpusEntryToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

