/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusSelectionResponseQualityMetrics } from './CorpusSelectionResponseQualityMetrics';
import {
    CorpusSelectionResponseQualityMetricsFromJSON,
    CorpusSelectionResponseQualityMetricsFromJSONTyped,
    CorpusSelectionResponseQualityMetricsToJSON,
    CorpusSelectionResponseQualityMetricsToJSONTyped,
} from './CorpusSelectionResponseQualityMetrics';

/**
 * 
 * @export
 * @interface CorpusSelectionResponse
 */
export interface CorpusSelectionResponse {
    /**
     * Unique identifier for this selection
     * @type {string}
     * @memberof CorpusSelectionResponse
     */
    selectionId: string;
    /**
     * IDs of selected corpus entries
     * @type {Array<string>}
     * @memberof CorpusSelectionResponse
     */
    selectedEntries: Array<string>;
    /**
     * Total coverage edges of selected corpus
     * @type {number}
     * @memberof CorpusSelectionResponse
     */
    totalCoverage: number;
    /**
     * Total size of selected corpus in bytes
     * @type {number}
     * @memberof CorpusSelectionResponse
     */
    totalSizeBytes?: number;
    /**
     * Time taken for selection
     * @type {number}
     * @memberof CorpusSelectionResponse
     */
    selectionTimeSeconds: number;
    /**
     * Selection strategy that was applied
     * @type {string}
     * @memberof CorpusSelectionResponse
     */
    strategyUsed?: string;
    /**
     * 
     * @type {CorpusSelectionResponseQualityMetrics}
     * @memberof CorpusSelectionResponse
     */
    qualityMetrics?: CorpusSelectionResponseQualityMetrics;
}

/**
 * Check if a given object implements the CorpusSelectionResponse interface.
 */
export function instanceOfCorpusSelectionResponse(value: object): value is CorpusSelectionResponse {
    if (!('selectionId' in value) || value['selectionId'] === undefined) return false;
    if (!('selectedEntries' in value) || value['selectedEntries'] === undefined) return false;
    if (!('totalCoverage' in value) || value['totalCoverage'] === undefined) return false;
    if (!('selectionTimeSeconds' in value) || value['selectionTimeSeconds'] === undefined) return false;
    return true;
}

export function CorpusSelectionResponseFromJSON(json: any): CorpusSelectionResponse {
    return CorpusSelectionResponseFromJSONTyped(json, false);
}

export function CorpusSelectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSelectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'selectionId': json['selection_id'],
        'selectedEntries': json['selected_entries'],
        'totalCoverage': json['total_coverage'],
        'totalSizeBytes': json['total_size_bytes'] == null ? undefined : json['total_size_bytes'],
        'selectionTimeSeconds': json['selection_time_seconds'],
        'strategyUsed': json['strategy_used'] == null ? undefined : json['strategy_used'],
        'qualityMetrics': json['quality_metrics'] == null ? undefined : CorpusSelectionResponseQualityMetricsFromJSON(json['quality_metrics']),
    };
}

export function CorpusSelectionResponseToJSON(json: any): CorpusSelectionResponse {
    return CorpusSelectionResponseToJSONTyped(json, false);
}

export function CorpusSelectionResponseToJSONTyped(value?: CorpusSelectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selection_id': value['selectionId'],
        'selected_entries': value['selectedEntries'],
        'total_coverage': value['totalCoverage'],
        'total_size_bytes': value['totalSizeBytes'],
        'selection_time_seconds': value['selectionTimeSeconds'],
        'strategy_used': value['strategyUsed'],
        'quality_metrics': CorpusSelectionResponseQualityMetricsToJSON(value['qualityMetrics']),
    };
}

