/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Selection criteria and preferences
 * @export
 * @interface CorpusSelectionRequestCriteria
 */
export interface CorpusSelectionRequestCriteria {
    /**
     * 
     * @type {number}
     * @memberof CorpusSelectionRequestCriteria
     */
    minCoverage?: number;
    /**
     * 
     * @type {number}
     * @memberof CorpusSelectionRequestCriteria
     */
    maxSizeBytes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CorpusSelectionRequestCriteria
     */
    preferSmallFiles?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CorpusSelectionRequestCriteria
     */
    includeEdgeCases?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CorpusSelectionRequestCriteria
     */
    minGeneration?: number;
}

/**
 * Check if a given object implements the CorpusSelectionRequestCriteria interface.
 */
export function instanceOfCorpusSelectionRequestCriteria(value: object): value is CorpusSelectionRequestCriteria {
    return true;
}

export function CorpusSelectionRequestCriteriaFromJSON(json: any): CorpusSelectionRequestCriteria {
    return CorpusSelectionRequestCriteriaFromJSONTyped(json, false);
}

export function CorpusSelectionRequestCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSelectionRequestCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'minCoverage': json['min_coverage'] == null ? undefined : json['min_coverage'],
        'maxSizeBytes': json['max_size_bytes'] == null ? undefined : json['max_size_bytes'],
        'preferSmallFiles': json['prefer_small_files'] == null ? undefined : json['prefer_small_files'],
        'includeEdgeCases': json['include_edge_cases'] == null ? undefined : json['include_edge_cases'],
        'minGeneration': json['min_generation'] == null ? undefined : json['min_generation'],
    };
}

export function CorpusSelectionRequestCriteriaToJSON(json: any): CorpusSelectionRequestCriteria {
    return CorpusSelectionRequestCriteriaToJSONTyped(json, false);
}

export function CorpusSelectionRequestCriteriaToJSONTyped(value?: CorpusSelectionRequestCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_coverage': value['minCoverage'],
        'max_size_bytes': value['maxSizeBytes'],
        'prefer_small_files': value['preferSmallFiles'],
        'include_edge_cases': value['includeEdgeCases'],
        'min_generation': value['minGeneration'],
    };
}

