/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusSyncResponseSummary } from './CorpusSyncResponseSummary';
import {
    CorpusSyncResponseSummaryFromJSON,
    CorpusSyncResponseSummaryFromJSONTyped,
    CorpusSyncResponseSummaryToJSON,
    CorpusSyncResponseSummaryToJSONTyped,
} from './CorpusSyncResponseSummary';

/**
 * 
 * @export
 * @interface CorpusSyncResponse
 */
export interface CorpusSyncResponse {
    /**
     * Unique identifier for this sync operation
     * @type {string}
     * @memberof CorpusSyncResponse
     */
    syncId: string;
    /**
     * Number of files successfully synced
     * @type {number}
     * @memberof CorpusSyncResponse
     */
    syncedFiles: number;
    /**
     * Number of files skipped (duplicates, etc.)
     * @type {number}
     * @memberof CorpusSyncResponse
     */
    skippedFiles?: number;
    /**
     * Total size of synced files in bytes
     * @type {number}
     * @memberof CorpusSyncResponse
     */
    totalSizeBytes: number;
    /**
     * Time taken for the sync operation
     * @type {number}
     * @memberof CorpusSyncResponse
     */
    durationSeconds: number;
    /**
     * Sync strategy that was applied
     * @type {string}
     * @memberof CorpusSyncResponse
     */
    strategyUsed: string;
    /**
     * 
     * @type {CorpusSyncResponseSummary}
     * @memberof CorpusSyncResponse
     */
    summary?: CorpusSyncResponseSummary;
}

/**
 * Check if a given object implements the CorpusSyncResponse interface.
 */
export function instanceOfCorpusSyncResponse(value: object): value is CorpusSyncResponse {
    if (!('syncId' in value) || value['syncId'] === undefined) return false;
    if (!('syncedFiles' in value) || value['syncedFiles'] === undefined) return false;
    if (!('totalSizeBytes' in value) || value['totalSizeBytes'] === undefined) return false;
    if (!('durationSeconds' in value) || value['durationSeconds'] === undefined) return false;
    if (!('strategyUsed' in value) || value['strategyUsed'] === undefined) return false;
    return true;
}

export function CorpusSyncResponseFromJSON(json: any): CorpusSyncResponse {
    return CorpusSyncResponseFromJSONTyped(json, false);
}

export function CorpusSyncResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSyncResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'syncId': json['sync_id'],
        'syncedFiles': json['synced_files'],
        'skippedFiles': json['skipped_files'] == null ? undefined : json['skipped_files'],
        'totalSizeBytes': json['total_size_bytes'],
        'durationSeconds': json['duration_seconds'],
        'strategyUsed': json['strategy_used'],
        'summary': json['summary'] == null ? undefined : CorpusSyncResponseSummaryFromJSON(json['summary']),
    };
}

export function CorpusSyncResponseToJSON(json: any): CorpusSyncResponse {
    return CorpusSyncResponseToJSONTyped(json, false);
}

export function CorpusSyncResponseToJSONTyped(value?: CorpusSyncResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sync_id': value['syncId'],
        'synced_files': value['syncedFiles'],
        'skipped_files': value['skippedFiles'],
        'total_size_bytes': value['totalSizeBytes'],
        'duration_seconds': value['durationSeconds'],
        'strategy_used': value['strategyUsed'],
        'summary': CorpusSyncResponseSummaryToJSON(value['summary']),
    };
}

