/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusSyncRequestFilters } from './CorpusSyncRequestFilters';
import {
    CorpusSyncRequestFiltersFromJSON,
    CorpusSyncRequestFiltersFromJSONTyped,
    CorpusSyncRequestFiltersToJSON,
    CorpusSyncRequestFiltersToJSONTyped,
} from './CorpusSyncRequestFilters';

/**
 * 
 * @export
 * @interface CorpusSyncRequest
 */
export interface CorpusSyncRequest {
    /**
     * Campaign to sync corpus from
     * @type {string}
     * @memberof CorpusSyncRequest
     */
    sourceCampaignId: string;
    /**
     * Campaign to sync corpus to
     * @type {string}
     * @memberof CorpusSyncRequest
     */
    targetCampaignId: string;
    /**
     * Strategy for selecting corpus to sync
     * @type {string}
     * @memberof CorpusSyncRequest
     */
    syncStrategy?: CorpusSyncRequestSyncStrategyEnum;
    /**
     * 
     * @type {CorpusSyncRequestFilters}
     * @memberof CorpusSyncRequest
     */
    filters?: CorpusSyncRequestFilters;
    /**
     * Maximum number of files to sync
     * @type {number}
     * @memberof CorpusSyncRequest
     */
    maxFiles?: number;
    /**
     * Whether to overwrite existing files with same hash
     * @type {boolean}
     * @memberof CorpusSyncRequest
     */
    overwriteDuplicates?: boolean;
}


/**
 * @export
 */
export const CorpusSyncRequestSyncStrategyEnum = {
    All: 'all',
    CoverageBased: 'coverage_based',
    SizeBased: 'size_based',
    TimeBased: 'time_based',
    Selective: 'selective'
} as const;
export type CorpusSyncRequestSyncStrategyEnum = typeof CorpusSyncRequestSyncStrategyEnum[keyof typeof CorpusSyncRequestSyncStrategyEnum];


/**
 * Check if a given object implements the CorpusSyncRequest interface.
 */
export function instanceOfCorpusSyncRequest(value: object): value is CorpusSyncRequest {
    if (!('sourceCampaignId' in value) || value['sourceCampaignId'] === undefined) return false;
    if (!('targetCampaignId' in value) || value['targetCampaignId'] === undefined) return false;
    return true;
}

export function CorpusSyncRequestFromJSON(json: any): CorpusSyncRequest {
    return CorpusSyncRequestFromJSONTyped(json, false);
}

export function CorpusSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceCampaignId': json['source_campaign_id'],
        'targetCampaignId': json['target_campaign_id'],
        'syncStrategy': json['sync_strategy'] == null ? undefined : json['sync_strategy'],
        'filters': json['filters'] == null ? undefined : CorpusSyncRequestFiltersFromJSON(json['filters']),
        'maxFiles': json['max_files'] == null ? undefined : json['max_files'],
        'overwriteDuplicates': json['overwrite_duplicates'] == null ? undefined : json['overwrite_duplicates'],
    };
}

export function CorpusSyncRequestToJSON(json: any): CorpusSyncRequest {
    return CorpusSyncRequestToJSONTyped(json, false);
}

export function CorpusSyncRequestToJSONTyped(value?: CorpusSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_campaign_id': value['sourceCampaignId'],
        'target_campaign_id': value['targetCampaignId'],
        'sync_strategy': value['syncStrategy'],
        'filters': CorpusSyncRequestFiltersToJSON(value['filters']),
        'max_files': value['maxFiles'],
        'overwrite_duplicates': value['overwriteDuplicates'],
    };
}

