/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Filters for corpus selection
 * @export
 * @interface CorpusSyncRequestFilters
 */
export interface CorpusSyncRequestFilters {
    /**
     * Minimum coverage edges required
     * @type {number}
     * @memberof CorpusSyncRequestFilters
     */
    minCoverage?: number;
    /**
     * Maximum file size to sync
     * @type {number}
     * @memberof CorpusSyncRequestFilters
     */
    maxSizeBytes?: number;
    /**
     * Only sync files created after this time
     * @type {Date}
     * @memberof CorpusSyncRequestFilters
     */
    createdAfter?: Date;
    /**
     * Only sync files with these tags
     * @type {Array<string>}
     * @memberof CorpusSyncRequestFilters
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the CorpusSyncRequestFilters interface.
 */
export function instanceOfCorpusSyncRequestFilters(value: object): value is CorpusSyncRequestFilters {
    return true;
}

export function CorpusSyncRequestFiltersFromJSON(json: any): CorpusSyncRequestFilters {
    return CorpusSyncRequestFiltersFromJSONTyped(json, false);
}

export function CorpusSyncRequestFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusSyncRequestFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'minCoverage': json['min_coverage'] == null ? undefined : json['min_coverage'],
        'maxSizeBytes': json['max_size_bytes'] == null ? undefined : json['max_size_bytes'],
        'createdAfter': json['created_after'] == null ? undefined : (new Date(json['created_after'])),
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CorpusSyncRequestFiltersToJSON(json: any): CorpusSyncRequestFilters {
    return CorpusSyncRequestFiltersToJSONTyped(json, false);
}

export function CorpusSyncRequestFiltersToJSONTyped(value?: CorpusSyncRequestFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_coverage': value['minCoverage'],
        'max_size_bytes': value['maxSizeBytes'],
        'created_after': value['createdAfter'] == null ? undefined : ((value['createdAfter']).toISOString()),
        'tags': value['tags'],
    };
}

