/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorpusUploadResponseErrorsInner } from './CorpusUploadResponseErrorsInner';
import {
    CorpusUploadResponseErrorsInnerFromJSON,
    CorpusUploadResponseErrorsInnerFromJSONTyped,
    CorpusUploadResponseErrorsInnerToJSON,
    CorpusUploadResponseErrorsInnerToJSONTyped,
} from './CorpusUploadResponseErrorsInner';

/**
 * 
 * @export
 * @interface CorpusUploadResponse
 */
export interface CorpusUploadResponse {
    /**
     * Number of files successfully uploaded
     * @type {number}
     * @memberof CorpusUploadResponse
     */
    uploadedCount: number;
    /**
     * Number of duplicate files skipped
     * @type {number}
     * @memberof CorpusUploadResponse
     */
    duplicateCount: number;
    /**
     * Number of files that failed to upload
     * @type {number}
     * @memberof CorpusUploadResponse
     */
    errorCount?: number;
    /**
     * Total size of uploaded files in bytes
     * @type {number}
     * @memberof CorpusUploadResponse
     */
    totalSizeBytes: number;
    /**
     * Unique identifier for this upload batch
     * @type {string}
     * @memberof CorpusUploadResponse
     */
    uploadId: string;
    /**
     * Details of any upload errors
     * @type {Array<CorpusUploadResponseErrorsInner>}
     * @memberof CorpusUploadResponse
     */
    errors?: Array<CorpusUploadResponseErrorsInner>;
    /**
     * Time taken to process the upload
     * @type {number}
     * @memberof CorpusUploadResponse
     */
    processingTimeSeconds?: number;
}

/**
 * Check if a given object implements the CorpusUploadResponse interface.
 */
export function instanceOfCorpusUploadResponse(value: object): value is CorpusUploadResponse {
    if (!('uploadedCount' in value) || value['uploadedCount'] === undefined) return false;
    if (!('duplicateCount' in value) || value['duplicateCount'] === undefined) return false;
    if (!('totalSizeBytes' in value) || value['totalSizeBytes'] === undefined) return false;
    if (!('uploadId' in value) || value['uploadId'] === undefined) return false;
    return true;
}

export function CorpusUploadResponseFromJSON(json: any): CorpusUploadResponse {
    return CorpusUploadResponseFromJSONTyped(json, false);
}

export function CorpusUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorpusUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadedCount': json['uploaded_count'],
        'duplicateCount': json['duplicate_count'],
        'errorCount': json['error_count'] == null ? undefined : json['error_count'],
        'totalSizeBytes': json['total_size_bytes'],
        'uploadId': json['upload_id'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(CorpusUploadResponseErrorsInnerFromJSON)),
        'processingTimeSeconds': json['processing_time_seconds'] == null ? undefined : json['processing_time_seconds'],
    };
}

export function CorpusUploadResponseToJSON(json: any): CorpusUploadResponse {
    return CorpusUploadResponseToJSONTyped(json, false);
}

export function CorpusUploadResponseToJSONTyped(value?: CorpusUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uploaded_count': value['uploadedCount'],
        'duplicate_count': value['duplicateCount'],
        'error_count': value['errorCount'],
        'total_size_bytes': value['totalSizeBytes'],
        'upload_id': value['uploadId'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(CorpusUploadResponseErrorsInnerToJSON)),
        'processing_time_seconds': value['processingTimeSeconds'],
    };
}

