/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoverageTrendsResponseDataPointsInner
 */
export interface CoverageTrendsResponseDataPointsInner {
    /**
     * 
     * @type {Date}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    totalEdges?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    newEdges?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    cumulativeEdges?: number;
    /**
     * Coverage per execution
     * @type {number}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    coverageDensity?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageTrendsResponseDataPointsInner
     */
    executionCount?: number;
}

/**
 * Check if a given object implements the CoverageTrendsResponseDataPointsInner interface.
 */
export function instanceOfCoverageTrendsResponseDataPointsInner(value: object): value is CoverageTrendsResponseDataPointsInner {
    return true;
}

export function CoverageTrendsResponseDataPointsInnerFromJSON(json: any): CoverageTrendsResponseDataPointsInner {
    return CoverageTrendsResponseDataPointsInnerFromJSONTyped(json, false);
}

export function CoverageTrendsResponseDataPointsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageTrendsResponseDataPointsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'totalEdges': json['total_edges'] == null ? undefined : json['total_edges'],
        'newEdges': json['new_edges'] == null ? undefined : json['new_edges'],
        'cumulativeEdges': json['cumulative_edges'] == null ? undefined : json['cumulative_edges'],
        'coverageDensity': json['coverage_density'] == null ? undefined : json['coverage_density'],
        'executionCount': json['execution_count'] == null ? undefined : json['execution_count'],
    };
}

export function CoverageTrendsResponseDataPointsInnerToJSON(json: any): CoverageTrendsResponseDataPointsInner {
    return CoverageTrendsResponseDataPointsInnerToJSONTyped(json, false);
}

export function CoverageTrendsResponseDataPointsInnerToJSONTyped(value?: CoverageTrendsResponseDataPointsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'total_edges': value['totalEdges'],
        'new_edges': value['newEdges'],
        'cumulative_edges': value['cumulativeEdges'],
        'coverage_density': value['coverageDensity'],
        'execution_count': value['executionCount'],
    };
}

