/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoverageTrendsResponseTimeRange
 */
export interface CoverageTrendsResponseTimeRange {
    /**
     * 
     * @type {Date}
     * @memberof CoverageTrendsResponseTimeRange
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CoverageTrendsResponseTimeRange
     */
    end?: Date;
}

/**
 * Check if a given object implements the CoverageTrendsResponseTimeRange interface.
 */
export function instanceOfCoverageTrendsResponseTimeRange(value: object): value is CoverageTrendsResponseTimeRange {
    return true;
}

export function CoverageTrendsResponseTimeRangeFromJSON(json: any): CoverageTrendsResponseTimeRange {
    return CoverageTrendsResponseTimeRangeFromJSONTyped(json, false);
}

export function CoverageTrendsResponseTimeRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageTrendsResponseTimeRange {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'] == null ? undefined : (new Date(json['start'])),
        'end': json['end'] == null ? undefined : (new Date(json['end'])),
    };
}

export function CoverageTrendsResponseTimeRangeToJSON(json: any): CoverageTrendsResponseTimeRange {
    return CoverageTrendsResponseTimeRangeToJSONTyped(json, false);
}

export function CoverageTrendsResponseTimeRangeToJSONTyped(value?: CoverageTrendsResponseTimeRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'start': value['start'] == null ? undefined : ((value['start']).toISOString()),
        'end': value['end'] == null ? undefined : ((value['end']).toISOString()),
    };
}

