/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { CoverageReport } from './CoverageReport';
import {
    CoverageReportFromJSON,
    CoverageReportFromJSONTyped,
    CoverageReportToJSON,
    CoverageReportToJSONTyped,
} from './CoverageReport';

/**
 * 
 * @export
 * @interface CoverageReportListResponse
 */
export interface CoverageReportListResponse {
    /**
     * 
     * @type {Array<CoverageReport>}
     * @memberof CoverageReportListResponse
     */
    data: Array<CoverageReport>;
    /**
     * 
     * @type {Pagination}
     * @memberof CoverageReportListResponse
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the CoverageReportListResponse interface.
 */
export function instanceOfCoverageReportListResponse(value: object): value is CoverageReportListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function CoverageReportListResponseFromJSON(json: any): CoverageReportListResponse {
    return CoverageReportListResponseFromJSONTyped(json, false);
}

export function CoverageReportListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageReportListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CoverageReportFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function CoverageReportListResponseToJSON(json: any): CoverageReportListResponse {
    return CoverageReportListResponseToJSONTyped(json, false);
}

export function CoverageReportListResponseToJSONTyped(value?: CoverageReportListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CoverageReportToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

