/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Coverage metrics summary
 * @export
 * @interface CoverageReportCoverageMetrics
 */
export interface CoverageReportCoverageMetrics {
    /**
     * Percentage of lines covered
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    lineCoveragePercent?: number;
    /**
     * Percentage of functions covered
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    functionCoveragePercent?: number;
    /**
     * Percentage of branches covered
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    branchCoveragePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    totalLines?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    coveredLines?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    totalFunctions?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    coveredFunctions?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    totalBranches?: number;
    /**
     * 
     * @type {number}
     * @memberof CoverageReportCoverageMetrics
     */
    coveredBranches?: number;
}

/**
 * Check if a given object implements the CoverageReportCoverageMetrics interface.
 */
export function instanceOfCoverageReportCoverageMetrics(value: object): value is CoverageReportCoverageMetrics {
    return true;
}

export function CoverageReportCoverageMetricsFromJSON(json: any): CoverageReportCoverageMetrics {
    return CoverageReportCoverageMetricsFromJSONTyped(json, false);
}

export function CoverageReportCoverageMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageReportCoverageMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'lineCoveragePercent': json['line_coverage_percent'] == null ? undefined : json['line_coverage_percent'],
        'functionCoveragePercent': json['function_coverage_percent'] == null ? undefined : json['function_coverage_percent'],
        'branchCoveragePercent': json['branch_coverage_percent'] == null ? undefined : json['branch_coverage_percent'],
        'totalLines': json['total_lines'] == null ? undefined : json['total_lines'],
        'coveredLines': json['covered_lines'] == null ? undefined : json['covered_lines'],
        'totalFunctions': json['total_functions'] == null ? undefined : json['total_functions'],
        'coveredFunctions': json['covered_functions'] == null ? undefined : json['covered_functions'],
        'totalBranches': json['total_branches'] == null ? undefined : json['total_branches'],
        'coveredBranches': json['covered_branches'] == null ? undefined : json['covered_branches'],
    };
}

export function CoverageReportCoverageMetricsToJSON(json: any): CoverageReportCoverageMetrics {
    return CoverageReportCoverageMetricsToJSONTyped(json, false);
}

export function CoverageReportCoverageMetricsToJSONTyped(value?: CoverageReportCoverageMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line_coverage_percent': value['lineCoveragePercent'],
        'function_coverage_percent': value['functionCoveragePercent'],
        'branch_coverage_percent': value['branchCoveragePercent'],
        'total_lines': value['totalLines'],
        'covered_lines': value['coveredLines'],
        'total_functions': value['totalFunctions'],
        'covered_functions': value['coveredFunctions'],
        'total_branches': value['totalBranches'],
        'covered_branches': value['coveredBranches'],
    };
}

