/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoverageFormat } from './CoverageFormat';
import {
    CoverageFormatFromJSON,
    CoverageFormatFromJSONTyped,
    CoverageFormatToJSON,
    CoverageFormatToJSONTyped,
} from './CoverageFormat';
import type { CoverageReportCoverageMetrics } from './CoverageReportCoverageMetrics';
import {
    CoverageReportCoverageMetricsFromJSON,
    CoverageReportCoverageMetricsFromJSONTyped,
    CoverageReportCoverageMetricsToJSON,
    CoverageReportCoverageMetricsToJSONTyped,
} from './CoverageReportCoverageMetrics';

/**
 * 
 * @export
 * @interface CoverageReport
 */
export interface CoverageReport {
    /**
     * Unique identifier for the coverage report
     * @type {string}
     * @memberof CoverageReport
     */
    id: string;
    /**
     * ID of the job that generated this report
     * @type {string}
     * @memberof CoverageReport
     */
    jobId: string;
    /**
     * 
     * @type {CoverageFormat}
     * @memberof CoverageReport
     */
    format: CoverageFormat;
    /**
     * Size of the coverage report in bytes
     * @type {number}
     * @memberof CoverageReport
     */
    sizeBytes: number;
    /**
     * When the coverage report was created
     * @type {Date}
     * @memberof CoverageReport
     */
    createdAt: Date;
    /**
     * SHA256 checksum of the report file
     * @type {string}
     * @memberof CoverageReport
     */
    checksum?: string;
    /**
     * 
     * @type {CoverageReportCoverageMetrics}
     * @memberof CoverageReport
     */
    coverageMetrics?: CoverageReportCoverageMetrics;
    /**
     * Path to the coverage report file in storage
     * @type {string}
     * @memberof CoverageReport
     */
    filePath?: string;
    /**
     * URL to download the coverage report
     * @type {string}
     * @memberof CoverageReport
     */
    downloadUrl?: string;
}



/**
 * Check if a given object implements the CoverageReport interface.
 */
export function instanceOfCoverageReport(value: object): value is CoverageReport {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('sizeBytes' in value) || value['sizeBytes'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CoverageReportFromJSON(json: any): CoverageReport {
    return CoverageReportFromJSONTyped(json, false);
}

export function CoverageReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoverageReport {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'jobId': json['job_id'],
        'format': CoverageFormatFromJSON(json['format']),
        'sizeBytes': json['size_bytes'],
        'createdAt': (new Date(json['created_at'])),
        'checksum': json['checksum'] == null ? undefined : json['checksum'],
        'coverageMetrics': json['coverage_metrics'] == null ? undefined : CoverageReportCoverageMetricsFromJSON(json['coverage_metrics']),
        'filePath': json['file_path'] == null ? undefined : json['file_path'],
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
    };
}

export function CoverageReportToJSON(json: any): CoverageReport {
    return CoverageReportToJSONTyped(json, false);
}

export function CoverageReportToJSONTyped(value?: CoverageReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'job_id': value['jobId'],
        'format': CoverageFormatToJSON(value['format']),
        'size_bytes': value['sizeBytes'],
        'created_at': ((value['createdAt']).toISOString()),
        'checksum': value['checksum'],
        'coverage_metrics': CoverageReportCoverageMetricsToJSON(value['coverageMetrics']),
        'file_path': value['filePath'],
        'download_url': value['downloadUrl'],
    };
}

