/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrashDeduplicationResponseSimilarCrashesInner } from './CrashDeduplicationResponseSimilarCrashesInner';
import {
    CrashDeduplicationResponseSimilarCrashesInnerFromJSON,
    CrashDeduplicationResponseSimilarCrashesInnerFromJSONTyped,
    CrashDeduplicationResponseSimilarCrashesInnerToJSON,
    CrashDeduplicationResponseSimilarCrashesInnerToJSONTyped,
} from './CrashDeduplicationResponseSimilarCrashesInner';

/**
 * 
 * @export
 * @interface CrashDeduplicationResponse
 */
export interface CrashDeduplicationResponse {
    /**
     * ID of the analyzed crash
     * @type {string}
     * @memberof CrashDeduplicationResponse
     */
    crashId: string;
    /**
     * Whether the crash is unique
     * @type {boolean}
     * @memberof CrashDeduplicationResponse
     */
    isUnique: boolean;
    /**
     * ID of the crash this is a duplicate of
     * @type {string}
     * @memberof CrashDeduplicationResponse
     */
    duplicateOf?: string | null;
    /**
     * Similarity score to the duplicate (0-1)
     * @type {number}
     * @memberof CrashDeduplicationResponse
     */
    similarityScore?: number;
    /**
     * Deduplication algorithm used
     * @type {string}
     * @memberof CrashDeduplicationResponse
     */
    algorithmUsed: string;
    /**
     * Group identifier assigned
     * @type {string}
     * @memberof CrashDeduplicationResponse
     */
    groupId?: string | null;
    /**
     * List of similar crashes found
     * @type {Array<CrashDeduplicationResponseSimilarCrashesInner>}
     * @memberof CrashDeduplicationResponse
     */
    similarCrashes?: Array<CrashDeduplicationResponseSimilarCrashesInner>;
    /**
     * Time taken for deduplication analysis
     * @type {number}
     * @memberof CrashDeduplicationResponse
     */
    processingTimeSeconds: number;
}

/**
 * Check if a given object implements the CrashDeduplicationResponse interface.
 */
export function instanceOfCrashDeduplicationResponse(value: object): value is CrashDeduplicationResponse {
    if (!('crashId' in value) || value['crashId'] === undefined) return false;
    if (!('isUnique' in value) || value['isUnique'] === undefined) return false;
    if (!('algorithmUsed' in value) || value['algorithmUsed'] === undefined) return false;
    if (!('processingTimeSeconds' in value) || value['processingTimeSeconds'] === undefined) return false;
    return true;
}

export function CrashDeduplicationResponseFromJSON(json: any): CrashDeduplicationResponse {
    return CrashDeduplicationResponseFromJSONTyped(json, false);
}

export function CrashDeduplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashDeduplicationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'crashId': json['crash_id'],
        'isUnique': json['is_unique'],
        'duplicateOf': json['duplicate_of'] == null ? undefined : json['duplicate_of'],
        'similarityScore': json['similarity_score'] == null ? undefined : json['similarity_score'],
        'algorithmUsed': json['algorithm_used'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'similarCrashes': json['similar_crashes'] == null ? undefined : ((json['similar_crashes'] as Array<any>).map(CrashDeduplicationResponseSimilarCrashesInnerFromJSON)),
        'processingTimeSeconds': json['processing_time_seconds'],
    };
}

export function CrashDeduplicationResponseToJSON(json: any): CrashDeduplicationResponse {
    return CrashDeduplicationResponseToJSONTyped(json, false);
}

export function CrashDeduplicationResponseToJSONTyped(value?: CrashDeduplicationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'crash_id': value['crashId'],
        'is_unique': value['isUnique'],
        'duplicate_of': value['duplicateOf'],
        'similarity_score': value['similarityScore'],
        'algorithm_used': value['algorithmUsed'],
        'group_id': value['groupId'],
        'similar_crashes': value['similarCrashes'] == null ? undefined : ((value['similarCrashes'] as Array<any>).map(CrashDeduplicationResponseSimilarCrashesInnerToJSON)),
        'processing_time_seconds': value['processingTimeSeconds'],
    };
}

