/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of crash detected
 * @export
 */
export const CrashType = {
    Segfault: 'segfault',
    Abort: 'abort',
    Timeout: 'timeout',
    Assertion: 'assertion',
    HeapOverflow: 'heap_overflow',
    StackOverflow: 'stack_overflow',
    UseAfterFree: 'use_after_free',
    DoubleFree: 'double_free',
    MemoryLeak: 'memory_leak',
    Other: 'other'
} as const;
export type CrashType = typeof CrashType[keyof typeof CrashType];


export function instanceOfCrashType(value: any): boolean {
    for (const key in CrashType) {
        if (Object.prototype.hasOwnProperty.call(CrashType, key)) {
            if (CrashType[key as keyof typeof CrashType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CrashTypeFromJSON(json: any): CrashType {
    return CrashTypeFromJSONTyped(json, false);
}

export function CrashTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashType {
    return json as CrashType;
}

export function CrashTypeToJSON(value?: CrashType | null): any {
    return value as any;
}

export function CrashTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CrashType {
    return value as CrashType;
}

