/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CrashSeverity } from './CrashSeverity';
import {
    CrashSeverityFromJSON,
    CrashSeverityFromJSONTyped,
    CrashSeverityToJSON,
    CrashSeverityToJSONTyped,
} from './CrashSeverity';
import type { CrashCrashInfo } from './CrashCrashInfo';
import {
    CrashCrashInfoFromJSON,
    CrashCrashInfoFromJSONTyped,
    CrashCrashInfoToJSON,
    CrashCrashInfoToJSONTyped,
} from './CrashCrashInfo';
import type { CrashReproductionInfo } from './CrashReproductionInfo';
import {
    CrashReproductionInfoFromJSON,
    CrashReproductionInfoFromJSONTyped,
    CrashReproductionInfoToJSON,
    CrashReproductionInfoToJSONTyped,
} from './CrashReproductionInfo';
import type { CrashType } from './CrashType';
import {
    CrashTypeFromJSON,
    CrashTypeFromJSONTyped,
    CrashTypeToJSON,
    CrashTypeToJSONTyped,
} from './CrashType';

/**
 * 
 * @export
 * @interface Crash
 */
export interface Crash {
    /**
     * Unique identifier for the crash
     * @type {string}
     * @memberof Crash
     */
    id: string;
    /**
     * SHA256 hash of the crash-inducing input
     * @type {string}
     * @memberof Crash
     */
    hash: string;
    /**
     * 
     * @type {CrashType}
     * @memberof Crash
     */
    type: CrashType;
    /**
     * 
     * @type {CrashSeverity}
     * @memberof Crash
     */
    severity: CrashSeverity;
    /**
     * ID of the campaign where crash was discovered
     * @type {string}
     * @memberof Crash
     */
    campaignId: string;
    /**
     * ID of the job that discovered the crash
     * @type {string}
     * @memberof Crash
     */
    jobId: string;
    /**
     * ID of the bot that discovered the crash
     * @type {string}
     * @memberof Crash
     */
    botId: string;
    /**
     * When the crash was discovered
     * @type {Date}
     * @memberof Crash
     */
    discoveredAt: Date;
    /**
     * Size of the crash-inducing input in bytes
     * @type {number}
     * @memberof Crash
     */
    inputSizeBytes: number;
    /**
     * Signal number that caused the crash
     * @type {number}
     * @memberof Crash
     */
    signal?: number;
    /**
     * Exit code of the crashed process
     * @type {number}
     * @memberof Crash
     */
    exitCode?: number;
    /**
     * Stack trace of the crash
     * @type {string}
     * @memberof Crash
     */
    stackTrace?: string;
    /**
     * 
     * @type {CrashCrashInfo}
     * @memberof Crash
     */
    crashInfo?: CrashCrashInfo;
    /**
     * 
     * @type {CrashReproductionInfo}
     * @memberof Crash
     */
    reproductionInfo?: CrashReproductionInfo;
    /**
     * Whether this crash is unique (not a duplicate)
     * @type {boolean}
     * @memberof Crash
     */
    isUnique?: boolean;
    /**
     * ID of the crash this is a duplicate of
     * @type {string}
     * @memberof Crash
     */
    duplicateOf?: string | null;
    /**
     * Group identifier for similar crashes
     * @type {string}
     * @memberof Crash
     */
    groupId?: string | null;
    /**
     * ID of the minimized crash input, if available
     * @type {string}
     * @memberof Crash
     */
    minimizedInputId?: string | null;
    /**
     * Whether this crash has been triaged
     * @type {boolean}
     * @memberof Crash
     */
    triaged?: boolean;
    /**
     * Triage priority (1=lowest, 10=highest)
     * @type {number}
     * @memberof Crash
     */
    priority?: number;
    /**
     * Tags for categorizing the crash
     * @type {Set<string>}
     * @memberof Crash
     */
    tags?: Set<string>;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof Crash
     */
    metadata?: { [key: string]: any; };
}



/**
 * Check if a given object implements the Crash interface.
 */
export function instanceOfCrash(value: object): value is Crash {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('botId' in value) || value['botId'] === undefined) return false;
    if (!('discoveredAt' in value) || value['discoveredAt'] === undefined) return false;
    if (!('inputSizeBytes' in value) || value['inputSizeBytes'] === undefined) return false;
    return true;
}

export function CrashFromJSON(json: any): Crash {
    return CrashFromJSONTyped(json, false);
}

export function CrashFromJSONTyped(json: any, ignoreDiscriminator: boolean): Crash {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hash': json['hash'],
        'type': CrashTypeFromJSON(json['type']),
        'severity': CrashSeverityFromJSON(json['severity']),
        'campaignId': json['campaign_id'],
        'jobId': json['job_id'],
        'botId': json['bot_id'],
        'discoveredAt': (new Date(json['discovered_at'])),
        'inputSizeBytes': json['input_size_bytes'],
        'signal': json['signal'] == null ? undefined : json['signal'],
        'exitCode': json['exit_code'] == null ? undefined : json['exit_code'],
        'stackTrace': json['stack_trace'] == null ? undefined : json['stack_trace'],
        'crashInfo': json['crash_info'] == null ? undefined : CrashCrashInfoFromJSON(json['crash_info']),
        'reproductionInfo': json['reproduction_info'] == null ? undefined : CrashReproductionInfoFromJSON(json['reproduction_info']),
        'isUnique': json['is_unique'] == null ? undefined : json['is_unique'],
        'duplicateOf': json['duplicate_of'] == null ? undefined : json['duplicate_of'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'minimizedInputId': json['minimized_input_id'] == null ? undefined : json['minimized_input_id'],
        'triaged': json['triaged'] == null ? undefined : json['triaged'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CrashToJSON(json: any): Crash {
    return CrashToJSONTyped(json, false);
}

export function CrashToJSONTyped(value?: Crash | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hash': value['hash'],
        'type': CrashTypeToJSON(value['type']),
        'severity': CrashSeverityToJSON(value['severity']),
        'campaign_id': value['campaignId'],
        'job_id': value['jobId'],
        'bot_id': value['botId'],
        'discovered_at': ((value['discoveredAt']).toISOString()),
        'input_size_bytes': value['inputSizeBytes'],
        'signal': value['signal'],
        'exit_code': value['exitCode'],
        'stack_trace': value['stackTrace'],
        'crash_info': CrashCrashInfoToJSON(value['crashInfo']),
        'reproduction_info': CrashReproductionInfoToJSON(value['reproductionInfo']),
        'is_unique': value['isUnique'],
        'duplicate_of': value['duplicateOf'],
        'group_id': value['groupId'],
        'minimized_input_id': value['minimizedInputId'],
        'triaged': value['triaged'],
        'priority': value['priority'],
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
        'metadata': value['metadata'],
    };
}

