/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';
import type { Crash } from './Crash';
import {
    CrashFromJSON,
    CrashFromJSONTyped,
    CrashToJSON,
    CrashToJSONTyped,
} from './Crash';

/**
 * 
 * @export
 * @interface CrashListResponse
 */
export interface CrashListResponse {
    /**
     * 
     * @type {Array<Crash>}
     * @memberof CrashListResponse
     */
    data: Array<Crash>;
    /**
     * 
     * @type {Pagination}
     * @memberof CrashListResponse
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the CrashListResponse interface.
 */
export function instanceOfCrashListResponse(value: object): value is CrashListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function CrashListResponseFromJSON(json: any): CrashListResponse {
    return CrashListResponseFromJSONTyped(json, false);
}

export function CrashListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CrashFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function CrashListResponseToJSON(json: any): CrashListResponse {
    return CrashListResponseToJSONTyped(json, false);
}

export function CrashListResponseToJSONTyped(value?: CrashListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CrashToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

