/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrashDeduplicationResponseSimilarCrashesInner
 */
export interface CrashDeduplicationResponseSimilarCrashesInner {
    /**
     * 
     * @type {string}
     * @memberof CrashDeduplicationResponseSimilarCrashesInner
     */
    crashId?: string;
    /**
     * 
     * @type {number}
     * @memberof CrashDeduplicationResponseSimilarCrashesInner
     */
    similarityScore?: number;
}

/**
 * Check if a given object implements the CrashDeduplicationResponseSimilarCrashesInner interface.
 */
export function instanceOfCrashDeduplicationResponseSimilarCrashesInner(value: object): value is CrashDeduplicationResponseSimilarCrashesInner {
    return true;
}

export function CrashDeduplicationResponseSimilarCrashesInnerFromJSON(json: any): CrashDeduplicationResponseSimilarCrashesInner {
    return CrashDeduplicationResponseSimilarCrashesInnerFromJSONTyped(json, false);
}

export function CrashDeduplicationResponseSimilarCrashesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashDeduplicationResponseSimilarCrashesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'crashId': json['crash_id'] == null ? undefined : json['crash_id'],
        'similarityScore': json['similarity_score'] == null ? undefined : json['similarity_score'],
    };
}

export function CrashDeduplicationResponseSimilarCrashesInnerToJSON(json: any): CrashDeduplicationResponseSimilarCrashesInner {
    return CrashDeduplicationResponseSimilarCrashesInnerToJSONTyped(json, false);
}

export function CrashDeduplicationResponseSimilarCrashesInnerToJSONTyped(value?: CrashDeduplicationResponseSimilarCrashesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'crash_id': value['crashId'],
        'similarity_score': value['similarityScore'],
    };
}

