/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Severity level of the crash
 * @export
 */
export const CrashSeverity = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type CrashSeverity = typeof CrashSeverity[keyof typeof CrashSeverity];


export function instanceOfCrashSeverity(value: any): boolean {
    for (const key in CrashSeverity) {
        if (Object.prototype.hasOwnProperty.call(CrashSeverity, key)) {
            if (CrashSeverity[key as keyof typeof CrashSeverity] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CrashSeverityFromJSON(json: any): CrashSeverity {
    return CrashSeverityFromJSONTyped(json, false);
}

export function CrashSeverityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashSeverity {
    return json as CrashSeverity;
}

export function CrashSeverityToJSON(value?: CrashSeverity | null): any {
    return value as any;
}

export function CrashSeverityToJSONTyped(value: any, ignoreDiscriminator: boolean): CrashSeverity {
    return value as CrashSeverity;
}

