/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Detailed crash analysis information
 * @export
 * @interface CrashCrashInfo
 */
export interface CrashCrashInfo {
    /**
     * Memory address where crash occurred
     * @type {string}
     * @memberof CrashCrashInfo
     */
    address?: string;
    /**
     * Instruction that caused the crash
     * @type {string}
     * @memberof CrashCrashInfo
     */
    instruction?: string;
    /**
     * CPU register values at crash time
     * @type {{ [key: string]: string; }}
     * @memberof CrashCrashInfo
     */
    registers?: { [key: string]: string; };
    /**
     * Memory mappings at crash time
     * @type {Array<string>}
     * @memberof CrashCrashInfo
     */
    memoryMaps?: Array<string>;
}

/**
 * Check if a given object implements the CrashCrashInfo interface.
 */
export function instanceOfCrashCrashInfo(value: object): value is CrashCrashInfo {
    return true;
}

export function CrashCrashInfoFromJSON(json: any): CrashCrashInfo {
    return CrashCrashInfoFromJSONTyped(json, false);
}

export function CrashCrashInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrashCrashInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'instruction': json['instruction'] == null ? undefined : json['instruction'],
        'registers': json['registers'] == null ? undefined : json['registers'],
        'memoryMaps': json['memory_maps'] == null ? undefined : json['memory_maps'],
    };
}

export function CrashCrashInfoToJSON(json: any): CrashCrashInfo {
    return CrashCrashInfoToJSONTyped(json, false);
}

export function CrashCrashInfoToJSONTyped(value?: CrashCrashInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'instruction': value['instruction'],
        'registers': value['registers'],
        'memory_maps': value['memoryMaps'],
    };
}

