/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeduplicateCrashRequest
 */
export interface DeduplicateCrashRequest {
    /**
     * 
     * @type {string}
     * @memberof DeduplicateCrashRequest
     */
    algorithm?: DeduplicateCrashRequestAlgorithmEnum;
    /**
     * Similarity threshold for fuzzy matching
     * @type {number}
     * @memberof DeduplicateCrashRequest
     */
    threshold?: number;
}


/**
 * @export
 */
export const DeduplicateCrashRequestAlgorithmEnum = {
    StackTrace: 'stack_trace',
    HashBased: 'hash_based',
    FuzzyMatching: 'fuzzy_matching'
} as const;
export type DeduplicateCrashRequestAlgorithmEnum = typeof DeduplicateCrashRequestAlgorithmEnum[keyof typeof DeduplicateCrashRequestAlgorithmEnum];


/**
 * Check if a given object implements the DeduplicateCrashRequest interface.
 */
export function instanceOfDeduplicateCrashRequest(value: object): value is DeduplicateCrashRequest {
    return true;
}

export function DeduplicateCrashRequestFromJSON(json: any): DeduplicateCrashRequest {
    return DeduplicateCrashRequestFromJSONTyped(json, false);
}

export function DeduplicateCrashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeduplicateCrashRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'] == null ? undefined : json['algorithm'],
        'threshold': json['threshold'] == null ? undefined : json['threshold'],
    };
}

export function DeduplicateCrashRequestToJSON(json: any): DeduplicateCrashRequest {
    return DeduplicateCrashRequestToJSONTyped(json, false);
}

export function DeduplicateCrashRequestToJSONTyped(value?: DeduplicateCrashRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'threshold': value['threshold'],
    };
}

