/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of fuzzer to use
 * @export
 */
export const FuzzerType = {
    Aflplusplus: 'aflplusplus',
    Libfuzzer: 'libfuzzer',
    Honggfuzz: 'honggfuzz'
} as const;
export type FuzzerType = typeof FuzzerType[keyof typeof FuzzerType];


export function instanceOfFuzzerType(value: any): boolean {
    for (const key in FuzzerType) {
        if (Object.prototype.hasOwnProperty.call(FuzzerType, key)) {
            if (FuzzerType[key as keyof typeof FuzzerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FuzzerTypeFromJSON(json: any): FuzzerType {
    return FuzzerTypeFromJSONTyped(json, false);
}

export function FuzzerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FuzzerType {
    return json as FuzzerType;
}

export function FuzzerTypeToJSON(value?: FuzzerType | null): any {
    return value as any;
}

export function FuzzerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FuzzerType {
    return value as FuzzerType;
}

