/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthStatusChecksValue
 */
export interface HealthStatusChecksValue {
    /**
     * 
     * @type {string}
     * @memberof HealthStatusChecksValue
     */
    status?: HealthStatusChecksValueStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof HealthStatusChecksValue
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof HealthStatusChecksValue
     */
    latencyMs?: number;
    /**
     * 
     * @type {Date}
     * @memberof HealthStatusChecksValue
     */
    lastCheck?: Date;
}


/**
 * @export
 */
export const HealthStatusChecksValueStatusEnum = {
    Healthy: 'healthy',
    Degraded: 'degraded',
    Unhealthy: 'unhealthy'
} as const;
export type HealthStatusChecksValueStatusEnum = typeof HealthStatusChecksValueStatusEnum[keyof typeof HealthStatusChecksValueStatusEnum];


/**
 * Check if a given object implements the HealthStatusChecksValue interface.
 */
export function instanceOfHealthStatusChecksValue(value: object): value is HealthStatusChecksValue {
    return true;
}

export function HealthStatusChecksValueFromJSON(json: any): HealthStatusChecksValue {
    return HealthStatusChecksValueFromJSONTyped(json, false);
}

export function HealthStatusChecksValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthStatusChecksValue {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
        'latencyMs': json['latency_ms'] == null ? undefined : json['latency_ms'],
        'lastCheck': json['last_check'] == null ? undefined : (new Date(json['last_check'])),
    };
}

export function HealthStatusChecksValueToJSON(json: any): HealthStatusChecksValue {
    return HealthStatusChecksValueToJSONTyped(json, false);
}

export function HealthStatusChecksValueToJSONTyped(value?: HealthStatusChecksValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
        'latency_ms': value['latencyMs'],
        'last_check': value['lastCheck'] == null ? undefined : ((value['lastCheck']).toISOString()),
    };
}

