/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';
import type { CoverageFormat } from './CoverageFormat';
import {
    CoverageFormatFromJSON,
    CoverageFormatFromJSONTyped,
    CoverageFormatToJSON,
    CoverageFormatToJSONTyped,
} from './CoverageFormat';
import type { FuzzerType } from './FuzzerType';
import {
    FuzzerTypeFromJSON,
    FuzzerTypeFromJSONTyped,
    FuzzerTypeToJSON,
    FuzzerTypeToJSONTyped,
} from './FuzzerType';
import type { JobProgress } from './JobProgress';
import {
    JobProgressFromJSON,
    JobProgressFromJSONTyped,
    JobProgressToJSON,
    JobProgressToJSONTyped,
} from './JobProgress';

/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * Unique identifier for the job
     * @type {string}
     * @memberof Job
     */
    id: string;
    /**
     * Human-readable name for the job
     * @type {string}
     * @memberof Job
     */
    name: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof Job
     */
    status: JobStatus;
    /**
     * 
     * @type {FuzzerType}
     * @memberof Job
     */
    fuzzer: FuzzerType;
    /**
     * Path to the target binary to fuzz
     * @type {string}
     * @memberof Job
     */
    targetBinary: string;
    /**
     * ID of the campaign this job belongs to
     * @type {string}
     * @memberof Job
     */
    campaignId?: string | null;
    /**
     * ID of the bot assigned to this job
     * @type {string}
     * @memberof Job
     */
    assignedBotId?: string | null;
    /**
     * When the job was created
     * @type {Date}
     * @memberof Job
     */
    createdAt: Date;
    /**
     * When the job started execution
     * @type {Date}
     * @memberof Job
     */
    startedAt?: Date | null;
    /**
     * When the job completed
     * @type {Date}
     * @memberof Job
     */
    completedAt?: Date | null;
    /**
     * When the job will timeout
     * @type {Date}
     * @memberof Job
     */
    timeoutAt: Date;
    /**
     * Job timeout in seconds
     * @type {number}
     * @memberof Job
     */
    timeoutSeconds?: number;
    /**
     * Fuzzer-specific configuration
     * @type {{ [key: string]: any; }}
     * @memberof Job
     */
    config?: { [key: string]: any; };
    /**
     * Whether to collect coverage information
     * @type {boolean}
     * @memberof Job
     */
    enableCoverage?: boolean;
    /**
     * 
     * @type {CoverageFormat}
     * @memberof Job
     */
    coverageFormat?: CoverageFormat;
    /**
     * Job priority (1=lowest, 10=highest)
     * @type {number}
     * @memberof Job
     */
    priority?: number;
    /**
     * 
     * @type {JobProgress}
     * @memberof Job
     */
    progress?: JobProgress;
    /**
     * Key-value metadata for extensibility
     * @type {{ [key: string]: any; }}
     * @memberof Job
     */
    metadata?: { [key: string]: any; };
}



/**
 * Check if a given object implements the Job interface.
 */
export function instanceOfJob(value: object): value is Job {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fuzzer' in value) || value['fuzzer'] === undefined) return false;
    if (!('targetBinary' in value) || value['targetBinary'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('timeoutAt' in value) || value['timeoutAt'] === undefined) return false;
    return true;
}

export function JobFromJSON(json: any): Job {
    return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'status': JobStatusFromJSON(json['status']),
        'fuzzer': FuzzerTypeFromJSON(json['fuzzer']),
        'targetBinary': json['target_binary'],
        'campaignId': json['campaign_id'] == null ? undefined : json['campaign_id'],
        'assignedBotId': json['assigned_bot_id'] == null ? undefined : json['assigned_bot_id'],
        'createdAt': (new Date(json['created_at'])),
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completedAt': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'timeoutAt': (new Date(json['timeout_at'])),
        'timeoutSeconds': json['timeout_seconds'] == null ? undefined : json['timeout_seconds'],
        'config': json['config'] == null ? undefined : json['config'],
        'enableCoverage': json['enable_coverage'] == null ? undefined : json['enable_coverage'],
        'coverageFormat': json['coverage_format'] == null ? undefined : CoverageFormatFromJSON(json['coverage_format']),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'progress': json['progress'] == null ? undefined : JobProgressFromJSON(json['progress']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function JobToJSON(json: any): Job {
    return JobToJSONTyped(json, false);
}

export function JobToJSONTyped(value?: Job | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': JobStatusToJSON(value['status']),
        'fuzzer': FuzzerTypeToJSON(value['fuzzer']),
        'target_binary': value['targetBinary'],
        'campaign_id': value['campaignId'],
        'assigned_bot_id': value['assignedBotId'],
        'created_at': ((value['createdAt']).toISOString()),
        'started_at': value['startedAt'] === null ? null : ((value['startedAt'] as any)?.toISOString()),
        'completed_at': value['completedAt'] === null ? null : ((value['completedAt'] as any)?.toISOString()),
        'timeout_at': ((value['timeoutAt']).toISOString()),
        'timeout_seconds': value['timeoutSeconds'],
        'config': value['config'],
        'enable_coverage': value['enableCoverage'],
        'coverage_format': CoverageFormatToJSON(value['coverageFormat']),
        'priority': value['priority'],
        'progress': JobProgressToJSON(value['progress']),
        'metadata': value['metadata'],
    };
}

