/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobLogsResponseLogsInner } from './JobLogsResponseLogsInner';
import {
    JobLogsResponseLogsInnerFromJSON,
    JobLogsResponseLogsInnerFromJSONTyped,
    JobLogsResponseLogsInnerToJSON,
    JobLogsResponseLogsInnerToJSONTyped,
} from './JobLogsResponseLogsInner';

/**
 * 
 * @export
 * @interface JobLogsResponse
 */
export interface JobLogsResponse {
    /**
     * ID of the job these logs belong to
     * @type {string}
     * @memberof JobLogsResponse
     */
    jobId: string;
    /**
     * 
     * @type {Array<JobLogsResponseLogsInner>}
     * @memberof JobLogsResponse
     */
    logs: Array<JobLogsResponseLogsInner>;
    /**
     * When the logs were retrieved
     * @type {Date}
     * @memberof JobLogsResponse
     */
    timestamp: Date;
    /**
     * Whether there are more logs available
     * @type {boolean}
     * @memberof JobLogsResponse
     */
    hasMore?: boolean;
}

/**
 * Check if a given object implements the JobLogsResponse interface.
 */
export function instanceOfJobLogsResponse(value: object): value is JobLogsResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('logs' in value) || value['logs'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function JobLogsResponseFromJSON(json: any): JobLogsResponse {
    return JobLogsResponseFromJSONTyped(json, false);
}

export function JobLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'logs': ((json['logs'] as Array<any>).map(JobLogsResponseLogsInnerFromJSON)),
        'timestamp': (new Date(json['timestamp'])),
        'hasMore': json['has_more'] == null ? undefined : json['has_more'],
    };
}

export function JobLogsResponseToJSON(json: any): JobLogsResponse {
    return JobLogsResponseToJSONTyped(json, false);
}

export function JobLogsResponseToJSONTyped(value?: JobLogsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'logs': ((value['logs'] as Array<any>).map(JobLogsResponseLogsInnerToJSON)),
        'timestamp': ((value['timestamp']).toISOString()),
        'has_more': value['hasMore'],
    };
}

