/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Current job progress
 * @export
 * @interface JobProgress
 */
export interface JobProgress {
    /**
     * Percentage completion
     * @type {number}
     * @memberof JobProgress
     */
    percentComplete?: number;
    /**
     * Number of executions performed
     * @type {number}
     * @memberof JobProgress
     */
    executions?: number;
    /**
     * Number of crashes found
     * @type {number}
     * @memberof JobProgress
     */
    crashesFound?: number;
    /**
     * Number of coverage edges discovered
     * @type {number}
     * @memberof JobProgress
     */
    coverageEdges?: number;
}

/**
 * Check if a given object implements the JobProgress interface.
 */
export function instanceOfJobProgress(value: object): value is JobProgress {
    return true;
}

export function JobProgressFromJSON(json: any): JobProgress {
    return JobProgressFromJSONTyped(json, false);
}

export function JobProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'percentComplete': json['percent_complete'] == null ? undefined : json['percent_complete'],
        'executions': json['executions'] == null ? undefined : json['executions'],
        'crashesFound': json['crashes_found'] == null ? undefined : json['crashes_found'],
        'coverageEdges': json['coverage_edges'] == null ? undefined : json['coverage_edges'],
    };
}

export function JobProgressToJSON(json: any): JobProgress {
    return JobProgressToJSONTyped(json, false);
}

export function JobProgressToJSONTyped(value?: JobProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent_complete': value['percentComplete'],
        'executions': value['executions'],
        'crashes_found': value['crashesFound'],
        'coverage_edges': value['coverageEdges'],
    };
}

