/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricsResponseMetricsSystem } from './MetricsResponseMetricsSystem';
import {
    MetricsResponseMetricsSystemFromJSON,
    MetricsResponseMetricsSystemFromJSONTyped,
    MetricsResponseMetricsSystemToJSON,
    MetricsResponseMetricsSystemToJSONTyped,
} from './MetricsResponseMetricsSystem';
import type { MetricsResponseMetricsCampaigns } from './MetricsResponseMetricsCampaigns';
import {
    MetricsResponseMetricsCampaignsFromJSON,
    MetricsResponseMetricsCampaignsFromJSONTyped,
    MetricsResponseMetricsCampaignsToJSON,
    MetricsResponseMetricsCampaignsToJSONTyped,
} from './MetricsResponseMetricsCampaigns';
import type { MetricsResponseMetricsBots } from './MetricsResponseMetricsBots';
import {
    MetricsResponseMetricsBotsFromJSON,
    MetricsResponseMetricsBotsFromJSONTyped,
    MetricsResponseMetricsBotsToJSON,
    MetricsResponseMetricsBotsToJSONTyped,
} from './MetricsResponseMetricsBots';
import type { MetricsResponseMetricsCoverage } from './MetricsResponseMetricsCoverage';
import {
    MetricsResponseMetricsCoverageFromJSON,
    MetricsResponseMetricsCoverageFromJSONTyped,
    MetricsResponseMetricsCoverageToJSON,
    MetricsResponseMetricsCoverageToJSONTyped,
} from './MetricsResponseMetricsCoverage';
import type { MetricsResponseMetricsJobs } from './MetricsResponseMetricsJobs';
import {
    MetricsResponseMetricsJobsFromJSON,
    MetricsResponseMetricsJobsFromJSONTyped,
    MetricsResponseMetricsJobsToJSON,
    MetricsResponseMetricsJobsToJSONTyped,
} from './MetricsResponseMetricsJobs';
import type { MetricsResponseMetricsCrashes } from './MetricsResponseMetricsCrashes';
import {
    MetricsResponseMetricsCrashesFromJSON,
    MetricsResponseMetricsCrashesFromJSONTyped,
    MetricsResponseMetricsCrashesToJSON,
    MetricsResponseMetricsCrashesToJSONTyped,
} from './MetricsResponseMetricsCrashes';

/**
 * Current system metrics
 * @export
 * @interface MetricsResponseMetrics
 */
export interface MetricsResponseMetrics {
    /**
     * 
     * @type {MetricsResponseMetricsBots}
     * @memberof MetricsResponseMetrics
     */
    bots?: MetricsResponseMetricsBots;
    /**
     * 
     * @type {MetricsResponseMetricsJobs}
     * @memberof MetricsResponseMetrics
     */
    jobs?: MetricsResponseMetricsJobs;
    /**
     * 
     * @type {MetricsResponseMetricsCampaigns}
     * @memberof MetricsResponseMetrics
     */
    campaigns?: MetricsResponseMetricsCampaigns;
    /**
     * 
     * @type {MetricsResponseMetricsCrashes}
     * @memberof MetricsResponseMetrics
     */
    crashes?: MetricsResponseMetricsCrashes;
    /**
     * 
     * @type {MetricsResponseMetricsCoverage}
     * @memberof MetricsResponseMetrics
     */
    coverage?: MetricsResponseMetricsCoverage;
    /**
     * 
     * @type {MetricsResponseMetricsSystem}
     * @memberof MetricsResponseMetrics
     */
    system?: MetricsResponseMetricsSystem;
}

/**
 * Check if a given object implements the MetricsResponseMetrics interface.
 */
export function instanceOfMetricsResponseMetrics(value: object): value is MetricsResponseMetrics {
    return true;
}

export function MetricsResponseMetricsFromJSON(json: any): MetricsResponseMetrics {
    return MetricsResponseMetricsFromJSONTyped(json, false);
}

export function MetricsResponseMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponseMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'bots': json['bots'] == null ? undefined : MetricsResponseMetricsBotsFromJSON(json['bots']),
        'jobs': json['jobs'] == null ? undefined : MetricsResponseMetricsJobsFromJSON(json['jobs']),
        'campaigns': json['campaigns'] == null ? undefined : MetricsResponseMetricsCampaignsFromJSON(json['campaigns']),
        'crashes': json['crashes'] == null ? undefined : MetricsResponseMetricsCrashesFromJSON(json['crashes']),
        'coverage': json['coverage'] == null ? undefined : MetricsResponseMetricsCoverageFromJSON(json['coverage']),
        'system': json['system'] == null ? undefined : MetricsResponseMetricsSystemFromJSON(json['system']),
    };
}

export function MetricsResponseMetricsToJSON(json: any): MetricsResponseMetrics {
    return MetricsResponseMetricsToJSONTyped(json, false);
}

export function MetricsResponseMetricsToJSONTyped(value?: MetricsResponseMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bots': MetricsResponseMetricsBotsToJSON(value['bots']),
        'jobs': MetricsResponseMetricsJobsToJSON(value['jobs']),
        'campaigns': MetricsResponseMetricsCampaignsToJSON(value['campaigns']),
        'crashes': MetricsResponseMetricsCrashesToJSON(value['crashes']),
        'coverage': MetricsResponseMetricsCoverageToJSON(value['coverage']),
        'system': MetricsResponseMetricsSystemToJSON(value['system']),
    };
}

