/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsResponseMetricsCrashes
 */
export interface MetricsResponseMetricsCrashes {
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCrashes
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCrashes
     */
    unique?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCrashes
     */
    today?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCrashes
     */
    critical?: number;
}

/**
 * Check if a given object implements the MetricsResponseMetricsCrashes interface.
 */
export function instanceOfMetricsResponseMetricsCrashes(value: object): value is MetricsResponseMetricsCrashes {
    return true;
}

export function MetricsResponseMetricsCrashesFromJSON(json: any): MetricsResponseMetricsCrashes {
    return MetricsResponseMetricsCrashesFromJSONTyped(json, false);
}

export function MetricsResponseMetricsCrashesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponseMetricsCrashes {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'unique': json['unique'] == null ? undefined : json['unique'],
        'today': json['today'] == null ? undefined : json['today'],
        'critical': json['critical'] == null ? undefined : json['critical'],
    };
}

export function MetricsResponseMetricsCrashesToJSON(json: any): MetricsResponseMetricsCrashes {
    return MetricsResponseMetricsCrashesToJSONTyped(json, false);
}

export function MetricsResponseMetricsCrashesToJSONTyped(value?: MetricsResponseMetricsCrashes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'unique': value['unique'],
        'today': value['today'],
        'critical': value['critical'],
    };
}

