/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsResponseMetricsCoverage
 */
export interface MetricsResponseMetricsCoverage {
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCoverage
     */
    totalEdges?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCoverage
     */
    edgesPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCoverage
     */
    growthRate?: number;
}

/**
 * Check if a given object implements the MetricsResponseMetricsCoverage interface.
 */
export function instanceOfMetricsResponseMetricsCoverage(value: object): value is MetricsResponseMetricsCoverage {
    return true;
}

export function MetricsResponseMetricsCoverageFromJSON(json: any): MetricsResponseMetricsCoverage {
    return MetricsResponseMetricsCoverageFromJSONTyped(json, false);
}

export function MetricsResponseMetricsCoverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponseMetricsCoverage {
    if (json == null) {
        return json;
    }
    return {
        
        'totalEdges': json['total_edges'] == null ? undefined : json['total_edges'],
        'edgesPerSecond': json['edges_per_second'] == null ? undefined : json['edges_per_second'],
        'growthRate': json['growth_rate'] == null ? undefined : json['growth_rate'],
    };
}

export function MetricsResponseMetricsCoverageToJSON(json: any): MetricsResponseMetricsCoverage {
    return MetricsResponseMetricsCoverageToJSONTyped(json, false);
}

export function MetricsResponseMetricsCoverageToJSONTyped(value?: MetricsResponseMetricsCoverage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_edges': value['totalEdges'],
        'edges_per_second': value['edgesPerSecond'],
        'growth_rate': value['growthRate'],
    };
}

