/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsResponseMetricsSystem
 */
export interface MetricsResponseMetricsSystem {
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    uptimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    cpuUsagePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    memoryUsageBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    diskUsageBytes?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    requestRatePerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsSystem
     */
    errorRatePerSecond?: number;
}

/**
 * Check if a given object implements the MetricsResponseMetricsSystem interface.
 */
export function instanceOfMetricsResponseMetricsSystem(value: object): value is MetricsResponseMetricsSystem {
    return true;
}

export function MetricsResponseMetricsSystemFromJSON(json: any): MetricsResponseMetricsSystem {
    return MetricsResponseMetricsSystemFromJSONTyped(json, false);
}

export function MetricsResponseMetricsSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponseMetricsSystem {
    if (json == null) {
        return json;
    }
    return {
        
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
        'cpuUsagePercent': json['cpu_usage_percent'] == null ? undefined : json['cpu_usage_percent'],
        'memoryUsageBytes': json['memory_usage_bytes'] == null ? undefined : json['memory_usage_bytes'],
        'diskUsageBytes': json['disk_usage_bytes'] == null ? undefined : json['disk_usage_bytes'],
        'requestRatePerSecond': json['request_rate_per_second'] == null ? undefined : json['request_rate_per_second'],
        'errorRatePerSecond': json['error_rate_per_second'] == null ? undefined : json['error_rate_per_second'],
    };
}

export function MetricsResponseMetricsSystemToJSON(json: any): MetricsResponseMetricsSystem {
    return MetricsResponseMetricsSystemToJSONTyped(json, false);
}

export function MetricsResponseMetricsSystemToJSONTyped(value?: MetricsResponseMetricsSystem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uptime_seconds': value['uptimeSeconds'],
        'cpu_usage_percent': value['cpuUsagePercent'],
        'memory_usage_bytes': value['memoryUsageBytes'],
        'disk_usage_bytes': value['diskUsageBytes'],
        'request_rate_per_second': value['requestRatePerSecond'],
        'error_rate_per_second': value['errorRatePerSecond'],
    };
}

