/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsResponseMetricsCampaigns
 */
export interface MetricsResponseMetricsCampaigns {
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCampaigns
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCampaigns
     */
    active?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCampaigns
     */
    paused?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsResponseMetricsCampaigns
     */
    completed?: number;
}

/**
 * Check if a given object implements the MetricsResponseMetricsCampaigns interface.
 */
export function instanceOfMetricsResponseMetricsCampaigns(value: object): value is MetricsResponseMetricsCampaigns {
    return true;
}

export function MetricsResponseMetricsCampaignsFromJSON(json: any): MetricsResponseMetricsCampaigns {
    return MetricsResponseMetricsCampaignsFromJSONTyped(json, false);
}

export function MetricsResponseMetricsCampaignsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsResponseMetricsCampaigns {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'active': json['active'] == null ? undefined : json['active'],
        'paused': json['paused'] == null ? undefined : json['paused'],
        'completed': json['completed'] == null ? undefined : json['completed'],
    };
}

export function MetricsResponseMetricsCampaignsToJSON(json: any): MetricsResponseMetricsCampaigns {
    return MetricsResponseMetricsCampaignsToJSONTyped(json, false);
}

export function MetricsResponseMetricsCampaignsToJSONTyped(value?: MetricsResponseMetricsCampaigns | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'active': value['active'],
        'paused': value['paused'],
        'completed': value['completed'],
    };
}

