/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MinimizeCrashRequest
 */
export interface MinimizeCrashRequest {
    /**
     * 
     * @type {string}
     * @memberof MinimizeCrashRequest
     */
    strategy?: MinimizeCrashRequestStrategyEnum;
    /**
     * 
     * @type {number}
     * @memberof MinimizeCrashRequest
     */
    timeoutSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof MinimizeCrashRequest
     */
    priority?: number;
}


/**
 * @export
 */
export const MinimizeCrashRequestStrategyEnum = {
    BinarySearch: 'binary_search',
    DeltaDebugging: 'delta_debugging',
    Hierarchical: 'hierarchical'
} as const;
export type MinimizeCrashRequestStrategyEnum = typeof MinimizeCrashRequestStrategyEnum[keyof typeof MinimizeCrashRequestStrategyEnum];


/**
 * Check if a given object implements the MinimizeCrashRequest interface.
 */
export function instanceOfMinimizeCrashRequest(value: object): value is MinimizeCrashRequest {
    return true;
}

export function MinimizeCrashRequestFromJSON(json: any): MinimizeCrashRequest {
    return MinimizeCrashRequestFromJSONTyped(json, false);
}

export function MinimizeCrashRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MinimizeCrashRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'strategy': json['strategy'] == null ? undefined : json['strategy'],
        'timeoutSeconds': json['timeout_seconds'] == null ? undefined : json['timeout_seconds'],
        'priority': json['priority'] == null ? undefined : json['priority'],
    };
}

export function MinimizeCrashRequestToJSON(json: any): MinimizeCrashRequest {
    return MinimizeCrashRequestToJSONTyped(json, false);
}

export function MinimizeCrashRequestToJSONTyped(value?: MinimizeCrashRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'strategy': value['strategy'],
        'timeout_seconds': value['timeoutSeconds'],
        'priority': value['priority'],
    };
}

