/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceStatsResponseOptimizationSuggestionsInner
 */
export interface PerformanceStatsResponseOptimizationSuggestionsInner {
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseOptimizationSuggestionsInner
     */
    category?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseOptimizationSuggestionsInner
     */
    suggestion?: string;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseOptimizationSuggestionsInner
     */
    estimatedImprovementPercent?: number;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseOptimizationSuggestionsInner
     */
    effortLevel?: PerformanceStatsResponseOptimizationSuggestionsInnerEffortLevelEnum;
}


/**
 * @export
 */
export const PerformanceStatsResponseOptimizationSuggestionsInnerEffortLevelEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high'
} as const;
export type PerformanceStatsResponseOptimizationSuggestionsInnerEffortLevelEnum = typeof PerformanceStatsResponseOptimizationSuggestionsInnerEffortLevelEnum[keyof typeof PerformanceStatsResponseOptimizationSuggestionsInnerEffortLevelEnum];


/**
 * Check if a given object implements the PerformanceStatsResponseOptimizationSuggestionsInner interface.
 */
export function instanceOfPerformanceStatsResponseOptimizationSuggestionsInner(value: object): value is PerformanceStatsResponseOptimizationSuggestionsInner {
    return true;
}

export function PerformanceStatsResponseOptimizationSuggestionsInnerFromJSON(json: any): PerformanceStatsResponseOptimizationSuggestionsInner {
    return PerformanceStatsResponseOptimizationSuggestionsInnerFromJSONTyped(json, false);
}

export function PerformanceStatsResponseOptimizationSuggestionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseOptimizationSuggestionsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'suggestion': json['suggestion'] == null ? undefined : json['suggestion'],
        'estimatedImprovementPercent': json['estimated_improvement_percent'] == null ? undefined : json['estimated_improvement_percent'],
        'effortLevel': json['effort_level'] == null ? undefined : json['effort_level'],
    };
}

export function PerformanceStatsResponseOptimizationSuggestionsInnerToJSON(json: any): PerformanceStatsResponseOptimizationSuggestionsInner {
    return PerformanceStatsResponseOptimizationSuggestionsInnerToJSONTyped(json, false);
}

export function PerformanceStatsResponseOptimizationSuggestionsInnerToJSONTyped(value?: PerformanceStatsResponseOptimizationSuggestionsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'suggestion': value['suggestion'],
        'estimated_improvement_percent': value['estimatedImprovementPercent'],
        'effort_level': value['effortLevel'],
    };
}

