/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceStatsResponseBottlenecksInner
 */
export interface PerformanceStatsResponseBottlenecksInner {
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseBottlenecksInner
     */
    component?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseBottlenecksInner
     */
    issue?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseBottlenecksInner
     */
    severity?: PerformanceStatsResponseBottlenecksInnerSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseBottlenecksInner
     */
    impact?: string;
    /**
     * 
     * @type {string}
     * @memberof PerformanceStatsResponseBottlenecksInner
     */
    recommendation?: string;
}


/**
 * @export
 */
export const PerformanceStatsResponseBottlenecksInnerSeverityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical'
} as const;
export type PerformanceStatsResponseBottlenecksInnerSeverityEnum = typeof PerformanceStatsResponseBottlenecksInnerSeverityEnum[keyof typeof PerformanceStatsResponseBottlenecksInnerSeverityEnum];


/**
 * Check if a given object implements the PerformanceStatsResponseBottlenecksInner interface.
 */
export function instanceOfPerformanceStatsResponseBottlenecksInner(value: object): value is PerformanceStatsResponseBottlenecksInner {
    return true;
}

export function PerformanceStatsResponseBottlenecksInnerFromJSON(json: any): PerformanceStatsResponseBottlenecksInner {
    return PerformanceStatsResponseBottlenecksInnerFromJSONTyped(json, false);
}

export function PerformanceStatsResponseBottlenecksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseBottlenecksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'component': json['component'] == null ? undefined : json['component'],
        'issue': json['issue'] == null ? undefined : json['issue'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'impact': json['impact'] == null ? undefined : json['impact'],
        'recommendation': json['recommendation'] == null ? undefined : json['recommendation'],
    };
}

export function PerformanceStatsResponseBottlenecksInnerToJSON(json: any): PerformanceStatsResponseBottlenecksInner {
    return PerformanceStatsResponseBottlenecksInnerToJSONTyped(json, false);
}

export function PerformanceStatsResponseBottlenecksInnerToJSONTyped(value?: PerformanceStatsResponseBottlenecksInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'component': value['component'],
        'issue': value['issue'],
        'severity': value['severity'],
        'impact': value['impact'],
        'recommendation': value['recommendation'],
    };
}

