/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceStatsResponseComponentStatsDatabase
 */
export interface PerformanceStatsResponseComponentStatsDatabase {
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsDatabase
     */
    avgQueryTimeMs?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsDatabase
     */
    connectionPoolUtilizationPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsDatabase
     */
    deadlockCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsDatabase
     */
    slowQueryCount?: number;
}

/**
 * Check if a given object implements the PerformanceStatsResponseComponentStatsDatabase interface.
 */
export function instanceOfPerformanceStatsResponseComponentStatsDatabase(value: object): value is PerformanceStatsResponseComponentStatsDatabase {
    return true;
}

export function PerformanceStatsResponseComponentStatsDatabaseFromJSON(json: any): PerformanceStatsResponseComponentStatsDatabase {
    return PerformanceStatsResponseComponentStatsDatabaseFromJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsDatabaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseComponentStatsDatabase {
    if (json == null) {
        return json;
    }
    return {
        
        'avgQueryTimeMs': json['avg_query_time_ms'] == null ? undefined : json['avg_query_time_ms'],
        'connectionPoolUtilizationPercent': json['connection_pool_utilization_percent'] == null ? undefined : json['connection_pool_utilization_percent'],
        'deadlockCount': json['deadlock_count'] == null ? undefined : json['deadlock_count'],
        'slowQueryCount': json['slow_query_count'] == null ? undefined : json['slow_query_count'],
    };
}

export function PerformanceStatsResponseComponentStatsDatabaseToJSON(json: any): PerformanceStatsResponseComponentStatsDatabase {
    return PerformanceStatsResponseComponentStatsDatabaseToJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsDatabaseToJSONTyped(value?: PerformanceStatsResponseComponentStatsDatabase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_query_time_ms': value['avgQueryTimeMs'],
        'connection_pool_utilization_percent': value['connectionPoolUtilizationPercent'],
        'deadlock_count': value['deadlockCount'],
        'slow_query_count': value['slowQueryCount'],
    };
}

