/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceStatsResponseComponentStats } from './PerformanceStatsResponseComponentStats';
import {
    PerformanceStatsResponseComponentStatsFromJSON,
    PerformanceStatsResponseComponentStatsFromJSONTyped,
    PerformanceStatsResponseComponentStatsToJSON,
    PerformanceStatsResponseComponentStatsToJSONTyped,
} from './PerformanceStatsResponseComponentStats';
import type { PerformanceStatsResponseOptimizationSuggestionsInner } from './PerformanceStatsResponseOptimizationSuggestionsInner';
import {
    PerformanceStatsResponseOptimizationSuggestionsInnerFromJSON,
    PerformanceStatsResponseOptimizationSuggestionsInnerFromJSONTyped,
    PerformanceStatsResponseOptimizationSuggestionsInnerToJSON,
    PerformanceStatsResponseOptimizationSuggestionsInnerToJSONTyped,
} from './PerformanceStatsResponseOptimizationSuggestionsInner';
import type { CoverageTrendsResponseTimeRange } from './CoverageTrendsResponseTimeRange';
import {
    CoverageTrendsResponseTimeRangeFromJSON,
    CoverageTrendsResponseTimeRangeFromJSONTyped,
    CoverageTrendsResponseTimeRangeToJSON,
    CoverageTrendsResponseTimeRangeToJSONTyped,
} from './CoverageTrendsResponseTimeRange';
import type { PerformanceStatsResponseBottlenecksInner } from './PerformanceStatsResponseBottlenecksInner';
import {
    PerformanceStatsResponseBottlenecksInnerFromJSON,
    PerformanceStatsResponseBottlenecksInnerFromJSONTyped,
    PerformanceStatsResponseBottlenecksInnerToJSON,
    PerformanceStatsResponseBottlenecksInnerToJSONTyped,
} from './PerformanceStatsResponseBottlenecksInner';

/**
 * 
 * @export
 * @interface PerformanceStatsResponse
 */
export interface PerformanceStatsResponse {
    /**
     * 
     * @type {CoverageTrendsResponseTimeRange}
     * @memberof PerformanceStatsResponse
     */
    timeRange: CoverageTrendsResponseTimeRange;
    /**
     * 
     * @type {PerformanceStatsResponseComponentStats}
     * @memberof PerformanceStatsResponse
     */
    componentStats: PerformanceStatsResponseComponentStats;
    /**
     * 
     * @type {Array<PerformanceStatsResponseBottlenecksInner>}
     * @memberof PerformanceStatsResponse
     */
    bottlenecks?: Array<PerformanceStatsResponseBottlenecksInner>;
    /**
     * 
     * @type {Array<PerformanceStatsResponseOptimizationSuggestionsInner>}
     * @memberof PerformanceStatsResponse
     */
    optimizationSuggestions?: Array<PerformanceStatsResponseOptimizationSuggestionsInner>;
}

/**
 * Check if a given object implements the PerformanceStatsResponse interface.
 */
export function instanceOfPerformanceStatsResponse(value: object): value is PerformanceStatsResponse {
    if (!('timeRange' in value) || value['timeRange'] === undefined) return false;
    if (!('componentStats' in value) || value['componentStats'] === undefined) return false;
    return true;
}

export function PerformanceStatsResponseFromJSON(json: any): PerformanceStatsResponse {
    return PerformanceStatsResponseFromJSONTyped(json, false);
}

export function PerformanceStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeRange': CoverageTrendsResponseTimeRangeFromJSON(json['time_range']),
        'componentStats': PerformanceStatsResponseComponentStatsFromJSON(json['component_stats']),
        'bottlenecks': json['bottlenecks'] == null ? undefined : ((json['bottlenecks'] as Array<any>).map(PerformanceStatsResponseBottlenecksInnerFromJSON)),
        'optimizationSuggestions': json['optimization_suggestions'] == null ? undefined : ((json['optimization_suggestions'] as Array<any>).map(PerformanceStatsResponseOptimizationSuggestionsInnerFromJSON)),
    };
}

export function PerformanceStatsResponseToJSON(json: any): PerformanceStatsResponse {
    return PerformanceStatsResponseToJSONTyped(json, false);
}

export function PerformanceStatsResponseToJSONTyped(value?: PerformanceStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'time_range': CoverageTrendsResponseTimeRangeToJSON(value['timeRange']),
        'component_stats': PerformanceStatsResponseComponentStatsToJSON(value['componentStats']),
        'bottlenecks': value['bottlenecks'] == null ? undefined : ((value['bottlenecks'] as Array<any>).map(PerformanceStatsResponseBottlenecksInnerToJSON)),
        'optimization_suggestions': value['optimizationSuggestions'] == null ? undefined : ((value['optimizationSuggestions'] as Array<any>).map(PerformanceStatsResponseOptimizationSuggestionsInnerToJSON)),
    };
}

