/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceStatsResponseComponentStatsJobs
 */
export interface PerformanceStatsResponseComponentStatsJobs {
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsJobs
     */
    avgQueueTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsJobs
     */
    avgExecutionTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsJobs
     */
    successRatePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsJobs
     */
    timeoutRatePercent?: number;
}

/**
 * Check if a given object implements the PerformanceStatsResponseComponentStatsJobs interface.
 */
export function instanceOfPerformanceStatsResponseComponentStatsJobs(value: object): value is PerformanceStatsResponseComponentStatsJobs {
    return true;
}

export function PerformanceStatsResponseComponentStatsJobsFromJSON(json: any): PerformanceStatsResponseComponentStatsJobs {
    return PerformanceStatsResponseComponentStatsJobsFromJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsJobsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseComponentStatsJobs {
    if (json == null) {
        return json;
    }
    return {
        
        'avgQueueTimeSeconds': json['avg_queue_time_seconds'] == null ? undefined : json['avg_queue_time_seconds'],
        'avgExecutionTimeSeconds': json['avg_execution_time_seconds'] == null ? undefined : json['avg_execution_time_seconds'],
        'successRatePercent': json['success_rate_percent'] == null ? undefined : json['success_rate_percent'],
        'timeoutRatePercent': json['timeout_rate_percent'] == null ? undefined : json['timeout_rate_percent'],
    };
}

export function PerformanceStatsResponseComponentStatsJobsToJSON(json: any): PerformanceStatsResponseComponentStatsJobs {
    return PerformanceStatsResponseComponentStatsJobsToJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsJobsToJSONTyped(value?: PerformanceStatsResponseComponentStatsJobs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_queue_time_seconds': value['avgQueueTimeSeconds'],
        'avg_execution_time_seconds': value['avgExecutionTimeSeconds'],
        'success_rate_percent': value['successRatePercent'],
        'timeout_rate_percent': value['timeoutRatePercent'],
    };
}

