/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformanceStatsResponseComponentStatsJobs } from './PerformanceStatsResponseComponentStatsJobs';
import {
    PerformanceStatsResponseComponentStatsJobsFromJSON,
    PerformanceStatsResponseComponentStatsJobsFromJSONTyped,
    PerformanceStatsResponseComponentStatsJobsToJSON,
    PerformanceStatsResponseComponentStatsJobsToJSONTyped,
} from './PerformanceStatsResponseComponentStatsJobs';
import type { PerformanceStatsResponseComponentStatsDatabase } from './PerformanceStatsResponseComponentStatsDatabase';
import {
    PerformanceStatsResponseComponentStatsDatabaseFromJSON,
    PerformanceStatsResponseComponentStatsDatabaseFromJSONTyped,
    PerformanceStatsResponseComponentStatsDatabaseToJSON,
    PerformanceStatsResponseComponentStatsDatabaseToJSONTyped,
} from './PerformanceStatsResponseComponentStatsDatabase';
import type { PerformanceStatsResponseComponentStatsBots } from './PerformanceStatsResponseComponentStatsBots';
import {
    PerformanceStatsResponseComponentStatsBotsFromJSON,
    PerformanceStatsResponseComponentStatsBotsFromJSONTyped,
    PerformanceStatsResponseComponentStatsBotsToJSON,
    PerformanceStatsResponseComponentStatsBotsToJSONTyped,
} from './PerformanceStatsResponseComponentStatsBots';
import type { PerformanceStatsResponseComponentStatsStorage } from './PerformanceStatsResponseComponentStatsStorage';
import {
    PerformanceStatsResponseComponentStatsStorageFromJSON,
    PerformanceStatsResponseComponentStatsStorageFromJSONTyped,
    PerformanceStatsResponseComponentStatsStorageToJSON,
    PerformanceStatsResponseComponentStatsStorageToJSONTyped,
} from './PerformanceStatsResponseComponentStatsStorage';

/**
 * 
 * @export
 * @interface PerformanceStatsResponseComponentStats
 */
export interface PerformanceStatsResponseComponentStats {
    /**
     * 
     * @type {PerformanceStatsResponseComponentStatsBots}
     * @memberof PerformanceStatsResponseComponentStats
     */
    bots?: PerformanceStatsResponseComponentStatsBots;
    /**
     * 
     * @type {PerformanceStatsResponseComponentStatsJobs}
     * @memberof PerformanceStatsResponseComponentStats
     */
    jobs?: PerformanceStatsResponseComponentStatsJobs;
    /**
     * 
     * @type {PerformanceStatsResponseComponentStatsStorage}
     * @memberof PerformanceStatsResponseComponentStats
     */
    storage?: PerformanceStatsResponseComponentStatsStorage;
    /**
     * 
     * @type {PerformanceStatsResponseComponentStatsDatabase}
     * @memberof PerformanceStatsResponseComponentStats
     */
    database?: PerformanceStatsResponseComponentStatsDatabase;
}

/**
 * Check if a given object implements the PerformanceStatsResponseComponentStats interface.
 */
export function instanceOfPerformanceStatsResponseComponentStats(value: object): value is PerformanceStatsResponseComponentStats {
    return true;
}

export function PerformanceStatsResponseComponentStatsFromJSON(json: any): PerformanceStatsResponseComponentStats {
    return PerformanceStatsResponseComponentStatsFromJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseComponentStats {
    if (json == null) {
        return json;
    }
    return {
        
        'bots': json['bots'] == null ? undefined : PerformanceStatsResponseComponentStatsBotsFromJSON(json['bots']),
        'jobs': json['jobs'] == null ? undefined : PerformanceStatsResponseComponentStatsJobsFromJSON(json['jobs']),
        'storage': json['storage'] == null ? undefined : PerformanceStatsResponseComponentStatsStorageFromJSON(json['storage']),
        'database': json['database'] == null ? undefined : PerformanceStatsResponseComponentStatsDatabaseFromJSON(json['database']),
    };
}

export function PerformanceStatsResponseComponentStatsToJSON(json: any): PerformanceStatsResponseComponentStats {
    return PerformanceStatsResponseComponentStatsToJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsToJSONTyped(value?: PerformanceStatsResponseComponentStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bots': PerformanceStatsResponseComponentStatsBotsToJSON(value['bots']),
        'jobs': PerformanceStatsResponseComponentStatsJobsToJSON(value['jobs']),
        'storage': PerformanceStatsResponseComponentStatsStorageToJSON(value['storage']),
        'database': PerformanceStatsResponseComponentStatsDatabaseToJSON(value['database']),
    };
}

