/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PerformanceStatsResponseComponentStatsBots
 */
export interface PerformanceStatsResponseComponentStatsBots {
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsBots
     */
    avgUtilizationPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsBots
     */
    avgJobCompletionTimeSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsBots
     */
    failureRatePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof PerformanceStatsResponseComponentStatsBots
     */
    throughputJobsPerHour?: number;
}

/**
 * Check if a given object implements the PerformanceStatsResponseComponentStatsBots interface.
 */
export function instanceOfPerformanceStatsResponseComponentStatsBots(value: object): value is PerformanceStatsResponseComponentStatsBots {
    return true;
}

export function PerformanceStatsResponseComponentStatsBotsFromJSON(json: any): PerformanceStatsResponseComponentStatsBots {
    return PerformanceStatsResponseComponentStatsBotsFromJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsBotsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformanceStatsResponseComponentStatsBots {
    if (json == null) {
        return json;
    }
    return {
        
        'avgUtilizationPercent': json['avg_utilization_percent'] == null ? undefined : json['avg_utilization_percent'],
        'avgJobCompletionTimeSeconds': json['avg_job_completion_time_seconds'] == null ? undefined : json['avg_job_completion_time_seconds'],
        'failureRatePercent': json['failure_rate_percent'] == null ? undefined : json['failure_rate_percent'],
        'throughputJobsPerHour': json['throughput_jobs_per_hour'] == null ? undefined : json['throughput_jobs_per_hour'],
    };
}

export function PerformanceStatsResponseComponentStatsBotsToJSON(json: any): PerformanceStatsResponseComponentStatsBots {
    return PerformanceStatsResponseComponentStatsBotsToJSONTyped(json, false);
}

export function PerformanceStatsResponseComponentStatsBotsToJSONTyped(value?: PerformanceStatsResponseComponentStatsBots | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_utilization_percent': value['avgUtilizationPercent'],
        'avg_job_completion_time_seconds': value['avgJobCompletionTimeSeconds'],
        'failure_rate_percent': value['failureRatePercent'],
        'throughput_jobs_per_hour': value['throughputJobsPerHour'],
    };
}

