/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RFC 7807 Problem Details for HTTP APIs
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * A URI reference that identifies the problem type
     * @type {string}
     * @memberof ProblemDetails
     */
    type: string;
    /**
     * A short, human-readable summary of the problem type
     * @type {string}
     * @memberof ProblemDetails
     */
    title: string;
    /**
     * The HTTP status code
     * @type {number}
     * @memberof ProblemDetails
     */
    status: number;
    /**
     * A human-readable explanation specific to this occurrence
     * @type {string}
     * @memberof ProblemDetails
     */
    detail?: string;
    /**
     * A URI reference that identifies the specific occurrence
     * @type {string}
     * @memberof ProblemDetails
     */
    instance?: string;
    /**
     * When the error occurred
     * @type {Date}
     * @memberof ProblemDetails
     */
    timestamp?: Date;
    /**
     * Request trace identifier for debugging
     * @type {string}
     * @memberof ProblemDetails
     */
    traceId?: string;
}

/**
 * Check if a given object implements the ProblemDetails interface.
 */
export function instanceOfProblemDetails(value: object): value is ProblemDetails {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProblemDetailsFromJSON(json: any): ProblemDetails {
    return ProblemDetailsFromJSONTyped(json, false);
}

export function ProblemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
    };
}

export function ProblemDetailsToJSON(json: any): ProblemDetails {
    return ProblemDetailsToJSONTyped(json, false);
}

export function ProblemDetailsToJSONTyped(value?: ProblemDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'trace_id': value['traceId'],
    };
}

