/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReproduceCrash202Response
 */
export interface ReproduceCrash202Response {
    /**
     * 
     * @type {string}
     * @memberof ReproduceCrash202Response
     */
    jobId?: string;
    /**
     * 
     * @type {string}
     * @memberof ReproduceCrash202Response
     */
    status?: ReproduceCrash202ResponseStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ReproduceCrash202Response
     */
    attemptsScheduled?: number;
}


/**
 * @export
 */
export const ReproduceCrash202ResponseStatusEnum = {
    Queued: 'queued'
} as const;
export type ReproduceCrash202ResponseStatusEnum = typeof ReproduceCrash202ResponseStatusEnum[keyof typeof ReproduceCrash202ResponseStatusEnum];


/**
 * Check if a given object implements the ReproduceCrash202Response interface.
 */
export function instanceOfReproduceCrash202Response(value: object): value is ReproduceCrash202Response {
    return true;
}

export function ReproduceCrash202ResponseFromJSON(json: any): ReproduceCrash202Response {
    return ReproduceCrash202ResponseFromJSONTyped(json, false);
}

export function ReproduceCrash202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReproduceCrash202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'] == null ? undefined : json['job_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'attemptsScheduled': json['attempts_scheduled'] == null ? undefined : json['attempts_scheduled'],
    };
}

export function ReproduceCrash202ResponseToJSON(json: any): ReproduceCrash202Response {
    return ReproduceCrash202ResponseToJSONTyped(json, false);
}

export function ReproduceCrash202ResponseToJSONTyped(value?: ReproduceCrash202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': value['status'],
        'attempts_scheduled': value['attemptsScheduled'],
    };
}

