/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopCampaignRequest
 */
export interface StopCampaignRequest {
    /**
     * Reason for stopping the campaign
     * @type {string}
     * @memberof StopCampaignRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the StopCampaignRequest interface.
 */
export function instanceOfStopCampaignRequest(value: object): value is StopCampaignRequest {
    return true;
}

export function StopCampaignRequestFromJSON(json: any): StopCampaignRequest {
    return StopCampaignRequestFromJSONTyped(json, false);
}

export function StopCampaignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopCampaignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function StopCampaignRequestToJSON(json: any): StopCampaignRequest {
    return StopCampaignRequestToJSONTyped(json, false);
}

export function StopCampaignRequestToJSONTyped(value?: StopCampaignRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

