# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.analytics_response import AnalyticsResponse

class TestAnalyticsResponse(unittest.TestCase):
    """AnalyticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsResponse:
        """Test AnalyticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsResponse`
        """
        model = AnalyticsResponse()
        if include_optional:
            return AnalyticsResponse(
                time_range = pandafuzz.models.analytics_response_time_range.AnalyticsResponse_time_range(
                    start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration = '', ),
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                system_overview = pandafuzz.models.analytics_response_system_overview.AnalyticsResponse_system_overview(
                    total_campaigns = 56, 
                    active_campaigns = 56, 
                    total_jobs = 56, 
                    active_jobs = 56, 
                    total_bots = 56, 
                    online_bots = 56, 
                    total_crashes = 56, 
                    unique_crashes = 56, 
                    total_corpus_entries = 56, 
                    total_coverage_edges = 56, ),
                performance_metrics = pandafuzz.models.analytics_response_performance_metrics.AnalyticsResponse_performance_metrics(
                    avg_job_completion_time_seconds = 1.337, 
                    avg_executions_per_second = 1.337, 
                    avg_coverage_per_hour = 1.337, 
                    crash_discovery_rate_per_hour = 1.337, 
                    system_efficiency_score = 0, ),
                resource_usage = pandafuzz.models.analytics_response_resource_usage.AnalyticsResponse_resource_usage(
                    cpu_utilization_percent = 1.337, 
                    memory_usage_bytes = 56, 
                    storage_usage_bytes = 56, 
                    network_throughput_bps = 56, ),
                trends = pandafuzz.models.analytics_response_trends.AnalyticsResponse_trends(
                    job_completion_trend = [
                        pandafuzz.models.analytics_response_trends_job_completion_trend_inner.AnalyticsResponse_trends_job_completion_trend_inner(
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            completed_jobs = 56, )
                        ], 
                    coverage_growth_trend = [
                        pandafuzz.models.analytics_response_trends_coverage_growth_trend_inner.AnalyticsResponse_trends_coverage_growth_trend_inner(
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            total_coverage = 56, )
                        ], 
                    crash_discovery_trend = [
                        pandafuzz.models.analytics_response_trends_crash_discovery_trend_inner.AnalyticsResponse_trends_crash_discovery_trend_inner(
                            timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            new_crashes = 56, )
                        ], )
            )
        else:
            return AnalyticsResponse(
                time_range = pandafuzz.models.analytics_response_time_range.AnalyticsResponse_time_range(
                    start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    duration = '', ),
                generated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                system_overview = pandafuzz.models.analytics_response_system_overview.AnalyticsResponse_system_overview(
                    total_campaigns = 56, 
                    active_campaigns = 56, 
                    total_jobs = 56, 
                    active_jobs = 56, 
                    total_bots = 56, 
                    online_bots = 56, 
                    total_crashes = 56, 
                    unique_crashes = 56, 
                    total_corpus_entries = 56, 
                    total_coverage_edges = 56, ),
        )
        """

    def testAnalyticsResponse(self):
        """Test AnalyticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
