# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.crash_deduplication_response import CrashDeduplicationResponse

class TestCrashDeduplicationResponse(unittest.TestCase):
    """CrashDeduplicationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CrashDeduplicationResponse:
        """Test CrashDeduplicationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CrashDeduplicationResponse`
        """
        model = CrashDeduplicationResponse()
        if include_optional:
            return CrashDeduplicationResponse(
                crash_id = '01234567-89ab-cdef-0123-456789abcdef',
                is_unique = False,
                duplicate_of = 'fedcba98-7654-3210-fedc-ba9876543210',
                similarity_score = 0.95,
                algorithm_used = 'stack_trace',
                group_id = 'crash-group-001',
                similar_crashes = [
                    pandafuzz.models.crash_deduplication_response_similar_crashes_inner.CrashDeduplicationResponse_similar_crashes_inner(
                        crash_id = '', 
                        similarity_score = 0, )
                    ],
                processing_time_seconds = 0.5
            )
        else:
            return CrashDeduplicationResponse(
                crash_id = '01234567-89ab-cdef-0123-456789abcdef',
                is_unique = False,
                algorithm_used = 'stack_trace',
                processing_time_seconds = 0.5,
        )
        """

    def testCrashDeduplicationResponse(self):
        """Test CrashDeduplicationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
