# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.artifact import Artifact

class TestArtifact(unittest.TestCase):
    """Artifact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Artifact:
        """Test Artifact
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Artifact`
        """
        model = Artifact()
        if include_optional:
            return Artifact(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                type = 'crash',
                filename = 'crash_001.bin',
                size_bytes = 1024,
                hash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
                job_id = '01234567-89ab-cdef-0123-456789abcdef',
                created_at = '2024-01-15T10:30Z',
                description = 'Crash input that triggers segmentation fault',
                content_type = 'application/octet-stream',
                download_url = '',
                metadata = {"region":"us-west-2","environment":"production","team":"security","priority":"high"}
            )
        else:
            return Artifact(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                type = 'crash',
                filename = 'crash_001.bin',
                size_bytes = 1024,
                hash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
                job_id = '01234567-89ab-cdef-0123-456789abcdef',
                created_at = '2024-01-15T10:30Z',
        )
        """

    def testArtifact(self):
        """Test Artifact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
