# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.batch_response import BatchResponse

class TestBatchResponse(unittest.TestCase):
    """BatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchResponse:
        """Test BatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchResponse`
        """
        model = BatchResponse()
        if include_optional:
            return BatchResponse(
                batch_id = '',
                total_operations = 0,
                successful_operations = 0,
                failed_operations = 0,
                execution_time_seconds = 0,
                results = [
                    pandafuzz.models.batch_response_results_inner.BatchResponse_results_inner(
                        operation_index = 0, 
                        operation = '', 
                        operation_id = '', 
                        status = 'success', 
                        result = pandafuzz.models.result.result(), 
                        error = pandafuzz.models.problem_details.ProblemDetails(
                            type = 'https://pandafuzz.ethpandaops.io/problems/job-already-running', 
                            title = 'Job Already Running', 
                            status = 409, 
                            detail = 'The job 01234567-89ab-cdef-0123-456789abcdef is already in running state', 
                            instance = '/api/v1/jobs/01234567-89ab-cdef-0123-456789abcdef', 
                            timestamp = '2024-01-15T10:30Z', 
                            trace_id = 'trace-12345-abcde', ), 
                        execution_time_seconds = 0, )
                    ],
                partial_success = True
            )
        else:
            return BatchResponse(
                batch_id = '',
                total_operations = 0,
                successful_operations = 0,
                failed_operations = 0,
                execution_time_seconds = 0,
                results = [
                    pandafuzz.models.batch_response_results_inner.BatchResponse_results_inner(
                        operation_index = 0, 
                        operation = '', 
                        operation_id = '', 
                        status = 'success', 
                        result = pandafuzz.models.result.result(), 
                        error = pandafuzz.models.problem_details.ProblemDetails(
                            type = 'https://pandafuzz.ethpandaops.io/problems/job-already-running', 
                            title = 'Job Already Running', 
                            status = 409, 
                            detail = 'The job 01234567-89ab-cdef-0123-456789abcdef is already in running state', 
                            instance = '/api/v1/jobs/01234567-89ab-cdef-0123-456789abcdef', 
                            timestamp = '2024-01-15T10:30Z', 
                            trace_id = 'trace-12345-abcde', ), 
                        execution_time_seconds = 0, )
                    ],
        )
        """

    def testBatchResponse(self):
        """Test BatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
