# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.corpus_entry_generation_info import CorpusEntryGenerationInfo

class TestCorpusEntryGenerationInfo(unittest.TestCase):
    """CorpusEntryGenerationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorpusEntryGenerationInfo:
        """Test CorpusEntryGenerationInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorpusEntryGenerationInfo`
        """
        model = CorpusEntryGenerationInfo()
        if include_optional:
            return CorpusEntryGenerationInfo(
                parent_hash = '',
                mutation_type = 'seed',
                generation = 0
            )
        else:
            return CorpusEntryGenerationInfo(
        )
        """

    def testCorpusEntryGenerationInfo(self):
        """Test CorpusEntryGenerationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
