# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.coverage_trends_response import CoverageTrendsResponse

class TestCoverageTrendsResponse(unittest.TestCase):
    """CoverageTrendsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CoverageTrendsResponse:
        """Test CoverageTrendsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoverageTrendsResponse`
        """
        model = CoverageTrendsResponse()
        if include_optional:
            return CoverageTrendsResponse(
                time_range = pandafuzz.models.coverage_trends_response_time_range.CoverageTrendsResponse_time_range(
                    start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                granularity = 'minute',
                campaign_id = '',
                data_points = [
                    pandafuzz.models.coverage_trends_response_data_points_inner.CoverageTrendsResponse_data_points_inner(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_edges = 56, 
                        new_edges = 56, 
                        cumulative_edges = 56, 
                        coverage_density = 1.337, 
                        execution_count = 56, )
                    ],
                summary = pandafuzz.models.coverage_trends_response_summary.CoverageTrendsResponse_summary(
                    total_growth = 56, 
                    growth_rate = 1.337, 
                    peak_discovery_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    efficiency_score = 0, )
            )
        else:
            return CoverageTrendsResponse(
                time_range = pandafuzz.models.coverage_trends_response_time_range.CoverageTrendsResponse_time_range(
                    start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                granularity = 'minute',
                data_points = [
                    pandafuzz.models.coverage_trends_response_data_points_inner.CoverageTrendsResponse_data_points_inner(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        total_edges = 56, 
                        new_edges = 56, 
                        cumulative_edges = 56, 
                        coverage_density = 1.337, 
                        execution_count = 56, )
                    ],
        )
        """

    def testCoverageTrendsResponse(self):
        """Test CoverageTrendsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
