# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.corpus_selection_request import CorpusSelectionRequest

class TestCorpusSelectionRequest(unittest.TestCase):
    """CorpusSelectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CorpusSelectionRequest:
        """Test CorpusSelectionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CorpusSelectionRequest`
        """
        model = CorpusSelectionRequest()
        if include_optional:
            return CorpusSelectionRequest(
                campaign_id = '01234567-89ab-cdef-0123-456789abcdef',
                selection_strategy = 'coverage_maximizing',
                max_entries = 100,
                criteria = pandafuzz.models.corpus_selection_request_criteria.CorpusSelectionRequest_criteria(
                    min_coverage = 0, 
                    max_size_bytes = 1, 
                    prefer_small_files = True, 
                    include_edge_cases = True, 
                    min_generation = 0, ),
                seed_corpus_weight = 0.2
            )
        else:
            return CorpusSelectionRequest(
                campaign_id = '01234567-89ab-cdef-0123-456789abcdef',
                selection_strategy = 'coverage_maximizing',
        )
        """

    def testCorpusSelectionRequest(self):
        """Test CorpusSelectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
