# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.performance_stats_response_component_stats import PerformanceStatsResponseComponentStats

class TestPerformanceStatsResponseComponentStats(unittest.TestCase):
    """PerformanceStatsResponseComponentStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PerformanceStatsResponseComponentStats:
        """Test PerformanceStatsResponseComponentStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PerformanceStatsResponseComponentStats`
        """
        model = PerformanceStatsResponseComponentStats()
        if include_optional:
            return PerformanceStatsResponseComponentStats(
                bots = pandafuzz.models.performance_stats_response_component_stats_bots.PerformanceStatsResponse_component_stats_bots(
                    avg_utilization_percent = 1.337, 
                    avg_job_completion_time_seconds = 1.337, 
                    failure_rate_percent = 1.337, 
                    throughput_jobs_per_hour = 1.337, ),
                jobs = pandafuzz.models.performance_stats_response_component_stats_jobs.PerformanceStatsResponse_component_stats_jobs(
                    avg_queue_time_seconds = 1.337, 
                    avg_execution_time_seconds = 1.337, 
                    success_rate_percent = 1.337, 
                    timeout_rate_percent = 1.337, ),
                storage = pandafuzz.models.performance_stats_response_component_stats_storage.PerformanceStatsResponse_component_stats_storage(
                    avg_read_latency_ms = 1.337, 
                    avg_write_latency_ms = 1.337, 
                    throughput_mbps = 1.337, 
                    error_rate_percent = 1.337, ),
                database = pandafuzz.models.performance_stats_response_component_stats_database.PerformanceStatsResponse_component_stats_database(
                    avg_query_time_ms = 1.337, 
                    connection_pool_utilization_percent = 1.337, 
                    deadlock_count = 56, 
                    slow_query_count = 56, )
            )
        else:
            return PerformanceStatsResponseComponentStats(
        )
        """

    def testPerformanceStatsResponseComponentStats(self):
        """Test PerformanceStatsResponseComponentStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
