# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.campaign_list_response import CampaignListResponse

class TestCampaignListResponse(unittest.TestCase):
    """CampaignListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CampaignListResponse:
        """Test CampaignListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignListResponse`
        """
        model = CampaignListResponse()
        if include_optional:
            return CampaignListResponse(
                data = [
                    pandafuzz.models.campaign.Campaign(
                        id = '01234567-89ab-cdef-0123-456789abcdef', 
                        name = 'HTTP Parser Security Test', 
                        description = 'Comprehensive security testing of HTTP parser implementation', 
                        status = 'active', 
                        target_binary = '/usr/bin/http-parser', 
                        target_hash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 
                        created_at = '2024-01-15T08:00Z', 
                        started_at = '2024-01-15T08:30Z', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        max_duration_seconds = 86400, 
                        max_jobs = 10, 
                        job_template = pandafuzz.models.campaign_job_template.Campaign_job_template(
                            fuzzer = 'libfuzzer', 
                            timeout_seconds = 60, 
                            config = { }, 
                            enable_coverage = True, 
                            coverage_format = 'json', ), 
                        auto_restart = True, 
                        shared_corpus = True, 
                        tags = ["security","parser","http"], 
                        metadata = {"region":"us-west-2","environment":"production","team":"security","priority":"high"}, )
                    ],
                pagination = pandafuzz.models.pagination.Pagination(
                    total = 1500, 
                    limit = 50, 
                    offset = 100, 
                    has_more = True, 
                    next_cursor = 'eyJpZCI6IjE1MCIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMTVUMTA6MzA6MDBaIn0=', 
                    prev_cursor = 'eyJpZCI6IjUwIiwidGltZXN0YW1wIjoiMjAyNC0wMS0xNVQwOTozMDowMFoifQ==', )
            )
        else:
            return CampaignListResponse(
                data = [
                    pandafuzz.models.campaign.Campaign(
                        id = '01234567-89ab-cdef-0123-456789abcdef', 
                        name = 'HTTP Parser Security Test', 
                        description = 'Comprehensive security testing of HTTP parser implementation', 
                        status = 'active', 
                        target_binary = '/usr/bin/http-parser', 
                        target_hash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 
                        created_at = '2024-01-15T08:00Z', 
                        started_at = '2024-01-15T08:30Z', 
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        max_duration_seconds = 86400, 
                        max_jobs = 10, 
                        job_template = pandafuzz.models.campaign_job_template.Campaign_job_template(
                            fuzzer = 'libfuzzer', 
                            timeout_seconds = 60, 
                            config = { }, 
                            enable_coverage = True, 
                            coverage_format = 'json', ), 
                        auto_restart = True, 
                        shared_corpus = True, 
                        tags = ["security","parser","http"], 
                        metadata = {"region":"us-west-2","environment":"production","team":"security","priority":"high"}, )
                    ],
                pagination = pandafuzz.models.pagination.Pagination(
                    total = 1500, 
                    limit = 50, 
                    offset = 100, 
                    has_more = True, 
                    next_cursor = 'eyJpZCI6IjE1MCIsInRpbWVzdGFtcCI6IjIwMjQtMDEtMTVUMTA6MzA6MDBaIn0=', 
                    prev_cursor = 'eyJpZCI6IjUwIiwidGltZXN0YW1wIjoiMjAyNC0wMS0xNVQwOTozMDowMFoifQ==', ),
        )
        """

    def testCampaignListResponse(self):
        """Test CampaignListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
