# coding: utf-8

"""
    PandaFuzz API

    PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 

    The version of the OpenAPI document: 1.0.0
    Contact: support@ethpandaops.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pandafuzz.models.job import Job

class TestJob(unittest.TestCase):
    """Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Job:
        """Test Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Job`
        """
        model = Job()
        if include_optional:
            return Job(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                name = 'libfuzzer-http-parser-test',
                status = 'running',
                fuzzer = 'libfuzzer',
                target_binary = '/usr/bin/http-parser',
                campaign_id = '01234567-89ab-cdef-0123-456789abcdef',
                assigned_bot_id = '01234567-89ab-cdef-0123-456789abcdef',
                created_at = '2024-01-15T10:00Z',
                started_at = '2024-01-15T10:05Z',
                completed_at = '2024-01-15T11:00Z',
                timeout_at = '2024-01-15T14:00Z',
                timeout_seconds = 3600,
                config = {"max_total_time":3600,"max_len":1024,"use_value_profile":true},
                enable_coverage = True,
                coverage_format = 'json',
                priority = 5,
                progress = pandafuzz.models.job_progress.Job_progress(
                    percent_complete = 0, 
                    executions = 0, 
                    crashes_found = 0, 
                    coverage_edges = 0, ),
                metadata = {"region":"us-west-2","environment":"production","team":"security","priority":"high"}
            )
        else:
            return Job(
                id = '01234567-89ab-cdef-0123-456789abcdef',
                name = 'libfuzzer-http-parser-test',
                status = 'running',
                fuzzer = 'libfuzzer',
                target_binary = '/usr/bin/http-parser',
                created_at = '2024-01-15T10:00Z',
                timeout_at = '2024-01-15T14:00Z',
        )
        """

    def testJob(self):
        """Test Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
