/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AnalyticsResponse,
  CoverageTrendsResponse,
  MetricsResponse,
  PerformanceStatsResponse,
  ProblemDetails,
} from '../models/index';
import {
    AnalyticsResponseFromJSON,
    AnalyticsResponseToJSON,
    CoverageTrendsResponseFromJSON,
    CoverageTrendsResponseToJSON,
    MetricsResponseFromJSON,
    MetricsResponseToJSON,
    PerformanceStatsResponseFromJSON,
    PerformanceStatsResponseToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface GetAnalyticsRequest {
    timeRange?: GetAnalyticsTimeRangeEnum;
    campaignId?: string;
    metrics?: string;
}

export interface GetCoverageTrendsRequest {
    campaignId?: string;
    timeRange?: GetCoverageTrendsTimeRangeEnum;
    granularity?: GetCoverageTrendsGranularityEnum;
}

export interface GetPerformanceStatsRequest {
    timeRange?: GetPerformanceStatsTimeRangeEnum;
    component?: GetPerformanceStatsComponentEnum;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Retrieve comprehensive analytics and metrics for the system
     * Get system analytics
     */
    async getAnalyticsRaw(requestParameters: GetAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AnalyticsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['campaignId'] != null) {
            queryParameters['campaign_id'] = requestParameters['campaignId'];
        }

        if (requestParameters['metrics'] != null) {
            queryParameters['metrics'] = requestParameters['metrics'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/analytics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AnalyticsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve comprehensive analytics and metrics for the system
     * Get system analytics
     */
    async getAnalytics(requestParameters: GetAnalyticsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AnalyticsResponse> {
        const response = await this.getAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve coverage analysis and trend data
     * Get coverage trends
     */
    async getCoverageTrendsRaw(requestParameters: GetCoverageTrendsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CoverageTrendsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['campaignId'] != null) {
            queryParameters['campaign_id'] = requestParameters['campaignId'];
        }

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['granularity'] != null) {
            queryParameters['granularity'] = requestParameters['granularity'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/analytics/coverage`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CoverageTrendsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve coverage analysis and trend data
     * Get coverage trends
     */
    async getCoverageTrends(requestParameters: GetCoverageTrendsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CoverageTrendsResponse> {
        const response = await this.getCoverageTrendsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve current system metrics and performance indicators
     * Get real-time metrics
     */
    async getMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetricsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/analytics/metrics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetricsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve current system metrics and performance indicators
     * Get real-time metrics
     */
    async getMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetricsResponse> {
        const response = await this.getMetricsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve performance metrics and bottleneck analysis
     * Get performance statistics
     */
    async getPerformanceStatsRaw(requestParameters: GetPerformanceStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformanceStatsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['timeRange'] != null) {
            queryParameters['time_range'] = requestParameters['timeRange'];
        }

        if (requestParameters['component'] != null) {
            queryParameters['component'] = requestParameters['component'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/analytics/performance`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformanceStatsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve performance metrics and bottleneck analysis
     * Get performance statistics
     */
    async getPerformanceStats(requestParameters: GetPerformanceStatsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformanceStatsResponse> {
        const response = await this.getPerformanceStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAnalyticsTimeRangeEnum = {
    _1h: '1h',
    _6h: '6h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetAnalyticsTimeRangeEnum = typeof GetAnalyticsTimeRangeEnum[keyof typeof GetAnalyticsTimeRangeEnum];
/**
 * @export
 */
export const GetCoverageTrendsTimeRangeEnum = {
    _1h: '1h',
    _6h: '6h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetCoverageTrendsTimeRangeEnum = typeof GetCoverageTrendsTimeRangeEnum[keyof typeof GetCoverageTrendsTimeRangeEnum];
/**
 * @export
 */
export const GetCoverageTrendsGranularityEnum = {
    Minute: 'minute',
    Hour: 'hour',
    Day: 'day'
} as const;
export type GetCoverageTrendsGranularityEnum = typeof GetCoverageTrendsGranularityEnum[keyof typeof GetCoverageTrendsGranularityEnum];
/**
 * @export
 */
export const GetPerformanceStatsTimeRangeEnum = {
    _1h: '1h',
    _6h: '6h',
    _24h: '24h',
    _7d: '7d',
    _30d: '30d'
} as const;
export type GetPerformanceStatsTimeRangeEnum = typeof GetPerformanceStatsTimeRangeEnum[keyof typeof GetPerformanceStatsTimeRangeEnum];
/**
 * @export
 */
export const GetPerformanceStatsComponentEnum = {
    Bots: 'bots',
    Jobs: 'jobs',
    Storage: 'storage',
    Database: 'database'
} as const;
export type GetPerformanceStatsComponentEnum = typeof GetPerformanceStatsComponentEnum[keyof typeof GetPerformanceStatsComponentEnum];
