/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bot,
  BotCreateRequest,
  BotHeartbeatRequest,
  BotHeartbeatResponse,
  BotListResponse,
  BotStatus,
  BotUpdateRequest,
  JobListResponse,
  JobStatus,
  ProblemDetails,
} from '../models/index';
import {
    BotFromJSON,
    BotToJSON,
    BotCreateRequestFromJSON,
    BotCreateRequestToJSON,
    BotHeartbeatRequestFromJSON,
    BotHeartbeatRequestToJSON,
    BotHeartbeatResponseFromJSON,
    BotHeartbeatResponseToJSON,
    BotListResponseFromJSON,
    BotListResponseToJSON,
    BotStatusFromJSON,
    BotStatusToJSON,
    BotUpdateRequestFromJSON,
    BotUpdateRequestToJSON,
    JobListResponseFromJSON,
    JobListResponseToJSON,
    JobStatusFromJSON,
    JobStatusToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface CreateBotRequest {
    botCreateRequest: BotCreateRequest;
}

export interface DeleteBotRequest {
    botId: string;
}

export interface GetBotRequest {
    botId: string;
    fields?: string;
}

export interface GetBotJobsRequest {
    botId: string;
    limit?: number;
    offset?: number;
    status?: JobStatus;
}

export interface ListBotsRequest {
    limit?: number;
    offset?: number;
    cursor?: string;
    fields?: string;
    status?: BotStatus;
    capabilities?: string;
    onlineOnly?: boolean;
    sort?: string;
}

export interface SendBotHeartbeatRequest {
    botId: string;
    botHeartbeatRequest: BotHeartbeatRequest;
}

export interface UpdateBotRequest {
    botId: string;
    botUpdateRequest: BotUpdateRequest;
}

/**
 * 
 */
export class BotsApi extends runtime.BaseAPI {

    /**
     * Register a new bot agent with the system
     * Register a new bot
     */
    async createBotRaw(requestParameters: CreateBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bot>> {
        if (requestParameters['botCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'botCreateRequest',
                'Required parameter "botCreateRequest" was null or undefined when calling createBot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotCreateRequestToJSON(requestParameters['botCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotFromJSON(jsonValue));
    }

    /**
     * Register a new bot agent with the system
     * Register a new bot
     */
    async createBot(requestParameters: CreateBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bot> {
        const response = await this.createBotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a bot from the system
     * Unregister bot
     */
    async deleteBotRaw(requestParameters: DeleteBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['botId'] == null) {
            throw new runtime.RequiredError(
                'botId',
                'Required parameter "botId" was null or undefined when calling deleteBot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots/{botId}`;
        urlPath = urlPath.replace(`{${"botId"}}`, encodeURIComponent(String(requestParameters['botId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a bot from the system
     * Unregister bot
     */
    async deleteBot(requestParameters: DeleteBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBotRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieve detailed information about a specific bot
     * Get bot details
     */
    async getBotRaw(requestParameters: GetBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bot>> {
        if (requestParameters['botId'] == null) {
            throw new runtime.RequiredError(
                'botId',
                'Required parameter "botId" was null or undefined when calling getBot().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots/{botId}`;
        urlPath = urlPath.replace(`{${"botId"}}`, encodeURIComponent(String(requestParameters['botId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific bot
     * Get bot details
     */
    async getBot(requestParameters: GetBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bot> {
        const response = await this.getBotRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve jobs assigned to or executed by this bot
     * Get bot jobs
     */
    async getBotJobsRaw(requestParameters: GetBotJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobListResponse>> {
        if (requestParameters['botId'] == null) {
            throw new runtime.RequiredError(
                'botId',
                'Required parameter "botId" was null or undefined when calling getBotJobs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots/{botId}/jobs`;
        urlPath = urlPath.replace(`{${"botId"}}`, encodeURIComponent(String(requestParameters['botId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobListResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve jobs assigned to or executed by this bot
     * Get bot jobs
     */
    async getBotJobs(requestParameters: GetBotJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobListResponse> {
        const response = await this.getBotJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a paginated list of registered bots with optional filtering
     * List bots
     */
    async listBotsRaw(requestParameters: ListBotsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BotListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['capabilities'] != null) {
            queryParameters['capabilities'] = requestParameters['capabilities'];
        }

        if (requestParameters['onlineOnly'] != null) {
            queryParameters['online_only'] = requestParameters['onlineOnly'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotListResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of registered bots with optional filtering
     * List bots
     */
    async listBots(requestParameters: ListBotsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BotListResponse> {
        const response = await this.listBotsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update bot status and last seen timestamp
     * Send bot heartbeat
     */
    async sendBotHeartbeatRaw(requestParameters: SendBotHeartbeatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BotHeartbeatResponse>> {
        if (requestParameters['botId'] == null) {
            throw new runtime.RequiredError(
                'botId',
                'Required parameter "botId" was null or undefined when calling sendBotHeartbeat().'
            );
        }

        if (requestParameters['botHeartbeatRequest'] == null) {
            throw new runtime.RequiredError(
                'botHeartbeatRequest',
                'Required parameter "botHeartbeatRequest" was null or undefined when calling sendBotHeartbeat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots/{botId}/heartbeat`;
        urlPath = urlPath.replace(`{${"botId"}}`, encodeURIComponent(String(requestParameters['botId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BotHeartbeatRequestToJSON(requestParameters['botHeartbeatRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotHeartbeatResponseFromJSON(jsonValue));
    }

    /**
     * Update bot status and last seen timestamp
     * Send bot heartbeat
     */
    async sendBotHeartbeat(requestParameters: SendBotHeartbeatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BotHeartbeatResponse> {
        const response = await this.sendBotHeartbeatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update bot information and configuration
     * Update bot
     */
    async updateBotRaw(requestParameters: UpdateBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Bot>> {
        if (requestParameters['botId'] == null) {
            throw new runtime.RequiredError(
                'botId',
                'Required parameter "botId" was null or undefined when calling updateBot().'
            );
        }

        if (requestParameters['botUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'botUpdateRequest',
                'Required parameter "botUpdateRequest" was null or undefined when calling updateBot().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/bots/{botId}`;
        urlPath = urlPath.replace(`{${"botId"}}`, encodeURIComponent(String(requestParameters['botId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BotUpdateRequestToJSON(requestParameters['botUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BotFromJSON(jsonValue));
    }

    /**
     * Update bot information and configuration
     * Update bot
     */
    async updateBot(requestParameters: UpdateBotRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Bot> {
        const response = await this.updateBotRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
