/* tslint:disable */
/* eslint-disable */
/**
 * PandaFuzz API
 * PandaFuzz distributed fuzzing orchestration platform API.  This API provides comprehensive access to all platform features including: - Bot management and orchestration - Job lifecycle management - Campaign coordination - Corpus synchronization and management - Crash analysis and deduplication - Real-time analytics and monitoring  ## Authentication The API supports both JWT Bearer tokens and API keys for authentication.  ## Rate Limiting API endpoints are rate-limited based on authentication method: - Authenticated requests: 1000 requests per hour - Unauthenticated requests: 100 requests per hour  ## Pagination List endpoints support both offset-based and cursor-based pagination.  ## Field Selection Use the `fields` query parameter to specify which fields to include in responses. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@ethpandaops.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Crash,
  CrashDeduplicationResponse,
  CrashListResponse,
  CrashSeverity,
  CrashType,
  DeduplicateCrashRequest,
  MinimizeCrash202Response,
  MinimizeCrashRequest,
  ProblemDetails,
  ReproduceCrash202Response,
  ReproduceCrashRequest,
} from '../models/index';
import {
    CrashFromJSON,
    CrashToJSON,
    CrashDeduplicationResponseFromJSON,
    CrashDeduplicationResponseToJSON,
    CrashListResponseFromJSON,
    CrashListResponseToJSON,
    CrashSeverityFromJSON,
    CrashSeverityToJSON,
    CrashTypeFromJSON,
    CrashTypeToJSON,
    DeduplicateCrashRequestFromJSON,
    DeduplicateCrashRequestToJSON,
    MinimizeCrash202ResponseFromJSON,
    MinimizeCrash202ResponseToJSON,
    MinimizeCrashRequestFromJSON,
    MinimizeCrashRequestToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    ReproduceCrash202ResponseFromJSON,
    ReproduceCrash202ResponseToJSON,
    ReproduceCrashRequestFromJSON,
    ReproduceCrashRequestToJSON,
} from '../models/index';

export interface DeduplicateCrashOperationRequest {
    crashId: string;
    deduplicateCrashRequest?: DeduplicateCrashRequest;
}

export interface GetCrashRequest {
    crashId: string;
    fields?: string;
}

export interface ListCrashesRequest {
    limit?: number;
    offset?: number;
    cursor?: string;
    fields?: string;
    campaignId?: string;
    jobId?: string;
    uniqueOnly?: boolean;
    crashType?: CrashType;
    severity?: CrashSeverity;
    sort?: string;
}

export interface MinimizeCrashOperationRequest {
    crashId: string;
    minimizeCrashRequest?: MinimizeCrashRequest;
}

export interface ReproduceCrashOperationRequest {
    crashId: string;
    reproduceCrashRequest?: ReproduceCrashRequest;
}

/**
 * 
 */
export class CrashesApi extends runtime.BaseAPI {

    /**
     * Find and group similar crashes using various deduplication algorithms
     * Deduplicate crash
     */
    async deduplicateCrashRaw(requestParameters: DeduplicateCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrashDeduplicationResponse>> {
        if (requestParameters['crashId'] == null) {
            throw new runtime.RequiredError(
                'crashId',
                'Required parameter "crashId" was null or undefined when calling deduplicateCrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crashes/{crashId}/deduplicate`;
        urlPath = urlPath.replace(`{${"crashId"}}`, encodeURIComponent(String(requestParameters['crashId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeduplicateCrashRequestToJSON(requestParameters['deduplicateCrashRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrashDeduplicationResponseFromJSON(jsonValue));
    }

    /**
     * Find and group similar crashes using various deduplication algorithms
     * Deduplicate crash
     */
    async deduplicateCrash(requestParameters: DeduplicateCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrashDeduplicationResponse> {
        const response = await this.deduplicateCrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve detailed information about a specific crash
     * Get crash details
     */
    async getCrashRaw(requestParameters: GetCrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Crash>> {
        if (requestParameters['crashId'] == null) {
            throw new runtime.RequiredError(
                'crashId',
                'Required parameter "crashId" was null or undefined when calling getCrash().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crashes/{crashId}`;
        urlPath = urlPath.replace(`{${"crashId"}}`, encodeURIComponent(String(requestParameters['crashId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrashFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a specific crash
     * Get crash details
     */
    async getCrash(requestParameters: GetCrashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Crash> {
        const response = await this.getCrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a paginated list of crashes with optional filtering
     * List crashes
     */
    async listCrashesRaw(requestParameters: ListCrashesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CrashListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['fields'] != null) {
            queryParameters['fields'] = requestParameters['fields'];
        }

        if (requestParameters['campaignId'] != null) {
            queryParameters['campaign_id'] = requestParameters['campaignId'];
        }

        if (requestParameters['jobId'] != null) {
            queryParameters['job_id'] = requestParameters['jobId'];
        }

        if (requestParameters['uniqueOnly'] != null) {
            queryParameters['unique_only'] = requestParameters['uniqueOnly'];
        }

        if (requestParameters['crashType'] != null) {
            queryParameters['crash_type'] = requestParameters['crashType'];
        }

        if (requestParameters['severity'] != null) {
            queryParameters['severity'] = requestParameters['severity'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crashes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CrashListResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a paginated list of crashes with optional filtering
     * List crashes
     */
    async listCrashes(requestParameters: ListCrashesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CrashListResponse> {
        const response = await this.listCrashesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a job to minimize the crash-triggering input
     * Minimize crash input
     */
    async minimizeCrashRaw(requestParameters: MinimizeCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MinimizeCrash202Response>> {
        if (requestParameters['crashId'] == null) {
            throw new runtime.RequiredError(
                'crashId',
                'Required parameter "crashId" was null or undefined when calling minimizeCrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crashes/{crashId}/minimize`;
        urlPath = urlPath.replace(`{${"crashId"}}`, encodeURIComponent(String(requestParameters['crashId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MinimizeCrashRequestToJSON(requestParameters['minimizeCrashRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MinimizeCrash202ResponseFromJSON(jsonValue));
    }

    /**
     * Create a job to minimize the crash-triggering input
     * Minimize crash input
     */
    async minimizeCrash(requestParameters: MinimizeCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MinimizeCrash202Response> {
        const response = await this.minimizeCrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a job to reproduce and verify the crash
     * Reproduce crash
     */
    async reproduceCrashRaw(requestParameters: ReproduceCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReproduceCrash202Response>> {
        if (requestParameters['crashId'] == null) {
            throw new runtime.RequiredError(
                'crashId',
                'Required parameter "crashId" was null or undefined when calling reproduceCrash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKeyAuth authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/crashes/{crashId}/reproduce`;
        urlPath = urlPath.replace(`{${"crashId"}}`, encodeURIComponent(String(requestParameters['crashId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReproduceCrashRequestToJSON(requestParameters['reproduceCrashRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReproduceCrash202ResponseFromJSON(jsonValue));
    }

    /**
     * Create a job to reproduce and verify the crash
     * Reproduce crash
     */
    async reproduceCrash(requestParameters: ReproduceCrashOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReproduceCrash202Response> {
        const response = await this.reproduceCrashRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
